-- ============================================================
-- JOB 관련 데이터 전체 조회
-- 용도: 특정 JOBID(템플릿/실행본)의 모든 설정과 실행 이력을 조회
-- 사용법: 아래 JOBID IN (...) 부분을 필요 시 변경
--   - 정확 매칭: JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
--   - LIKE 매칭: 실행본(예: ..._20260208) 까지 함께 조회 시 [B] 섹션 사용
-- ============================================================


-- ============================================================
-- [A] 정확 매칭 — 템플릿 JOBID 만 조회
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- [A-0] 건수 요약 (한 눈에 보기)
-- ────────────────────────────────────────────────────────────
SELECT 'TBL_PIIJOB'                  AS TBL, COUNT(*) AS CNT FROM COTDL.TBL_PIIJOB                  WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIJOBWAIT',                COUNT(*) FROM COTDL.TBL_PIIJOBWAIT                WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIISTEP',                   COUNT(*) FROM COTDL.TBL_PIISTEP                   WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIISTEPTABLE',              COUNT(*) FROM COTDL.TBL_PIISTEPTABLE              WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIISTEPTABLEWAIT',          COUNT(*) FROM COTDL.TBL_PIISTEPTABLEWAIT          WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIISTEPTABLEUPDATE',        COUNT(*) FROM COTDL.TBL_PIISTEPTABLEUPDATE        WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIISTEPTABLE_ETC',          COUNT(*) FROM COTDL.TBL_PIISTEPTABLE_ETC          WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIORDER',                  COUNT(*) FROM COTDL.TBL_PIIORDER                  WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIORDERJOBWAIT',           COUNT(*) FROM COTDL.TBL_PIIORDERJOBWAIT           WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIORDERSTEP',              COUNT(*) FROM COTDL.TBL_PIIORDERSTEP              WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIORDERSTEPTABLE',         COUNT(*) FROM COTDL.TBL_PIIORDERSTEPTABLE         WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIORDERSTEPTABLEWAIT',     COUNT(*) FROM COTDL.TBL_PIIORDERSTEPTABLEWAIT     WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIORDERSTEPTABLEUPDATE',   COUNT(*) FROM COTDL.TBL_PIIORDERSTEPTABLEUPDATE   WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIORDERTHREAD',            COUNT(*) FROM COTDL.TBL_PIIORDERTHREAD            WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIAPPROVALREQ',            COUNT(*) FROM COTDL.TBL_PIIAPPROVALREQ            WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIRESTORE',                COUNT(*) FROM COTDL.TBL_PIIRESTORE                WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIRECOVERY',               COUNT(*) FROM COTDL.TBL_PIIRECOVERY               WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIEXTRACT',                COUNT(*) FROM COTDL.TBL_PIIEXTRACT                WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIEXTRACT_PURGE_STAT',     COUNT(*) FROM COTDL.TBL_PIIEXTRACT_PURGE_STAT     WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIEXTRACT_PURGE_LOG',      COUNT(*) FROM COTDL.TBL_PIIEXTRACT_PURGE_LOG      WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_TESTDATA',                  COUNT(*) FROM COTDL.TBL_TESTDATA                  WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
UNION ALL SELECT 'TBL_PIIUPLOAD_TEMPLATE',        COUNT(*) FROM COTDL.TBL_PIIUPLOAD_TEMPLATE        WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE');


-- ────────────────────────────────────────────────────────────
-- [A-1] JOB 본체 / 정의
-- ────────────────────────────────────────────────────────────
SELECT * FROM COTDL.TBL_PIIJOB
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY JOBID;

SELECT * FROM COTDL.TBL_PIIJOBWAIT
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY JOBID;


-- ────────────────────────────────────────────────────────────
-- [A-2] STEP / STEPTABLE 정의
-- ────────────────────────────────────────────────────────────
SELECT * FROM COTDL.TBL_PIISTEP
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY JOBID, VERSION, SEQ1, SEQ2, SEQ3;

SELECT * FROM COTDL.TBL_PIISTEPTABLE
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY JOBID, VERSION, STEPID, SEQ1, SEQ2, SEQ3;

SELECT * FROM COTDL.TBL_PIISTEPTABLEWAIT
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY JOBID, VERSION, STEPID;

SELECT * FROM COTDL.TBL_PIISTEPTABLEUPDATE
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY JOBID, VERSION, STEPID;

SELECT * FROM COTDL.TBL_PIISTEPTABLE_ETC
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY JOBID, VERSION, STEPID, SEQ1, SEQ2, SEQ3;


-- ────────────────────────────────────────────────────────────
-- [A-3] ORDER (실행 인스턴스) 관련
-- ────────────────────────────────────────────────────────────
SELECT * FROM COTDL.TBL_PIIORDER
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY ORDERID DESC;

SELECT * FROM COTDL.TBL_PIIORDERJOBWAIT
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY ORDERID DESC;

SELECT * FROM COTDL.TBL_PIIORDERSTEP
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY ORDERID DESC, STEPID;

SELECT * FROM COTDL.TBL_PIIORDERSTEPTABLE
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY ORDERID DESC, STEPID;

SELECT * FROM COTDL.TBL_PIIORDERSTEPTABLEWAIT
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY ORDERID DESC;

SELECT * FROM COTDL.TBL_PIIORDERSTEPTABLEUPDATE
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY ORDERID DESC;

SELECT * FROM COTDL.TBL_PIIORDERTHREAD
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY ORDERID DESC;


-- ────────────────────────────────────────────────────────────
-- [A-4] 결재 / 복구 / 추출 / 파기
-- ────────────────────────────────────────────────────────────
SELECT * FROM COTDL.TBL_PIIAPPROVALREQ
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY REGDATE DESC;

SELECT * FROM COTDL.TBL_PIIRESTORE
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY ORDERID DESC;

SELECT * FROM COTDL.TBL_PIIRECOVERY
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY ORDERID DESC;

SELECT * FROM COTDL.TBL_PIIEXTRACT
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY ORDERID DESC;

SELECT * FROM COTDL.TBL_PIIEXTRACT_PURGE_STAT
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY ORDERID DESC;

SELECT * FROM COTDL.TBL_PIIEXTRACT_PURGE_LOG
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE')
 ORDER BY ORDERID DESC;


-- ────────────────────────────────────────────────────────────
-- [A-5] 기타 (테스트데이터 / 업로드 템플릿)
-- ────────────────────────────────────────────────────────────
SELECT * FROM COTDL.TBL_TESTDATA
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE');

SELECT * FROM COTDL.TBL_PIIUPLOAD_TEMPLATE
 WHERE JOBID IN ('PII_POLICY3_DAON_CORE_DELETE','PII_POLICY3_DAON_CORE_UPDATE');




-- ============================================================
-- [B] LIKE 매칭 — 실행본(예: ..._YYYYMMDD) 까지 포함
--     템플릿 + 자동 생성된 실행 인스턴스를 한꺼번에 조회할 때 사용
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- [B-0] 건수 요약 (LIKE)
-- ────────────────────────────────────────────────────────────
SELECT 'TBL_PIIJOB'                  AS TBL, COUNT(*) AS CNT FROM COTDL.TBL_PIIJOB                  WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIJOBWAIT',                COUNT(*) FROM COTDL.TBL_PIIJOBWAIT                WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIISTEP',                   COUNT(*) FROM COTDL.TBL_PIISTEP                   WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIISTEPTABLE',              COUNT(*) FROM COTDL.TBL_PIISTEPTABLE              WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIISTEPTABLEWAIT',          COUNT(*) FROM COTDL.TBL_PIISTEPTABLEWAIT          WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIISTEPTABLEUPDATE',        COUNT(*) FROM COTDL.TBL_PIISTEPTABLEUPDATE        WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIISTEPTABLE_ETC',          COUNT(*) FROM COTDL.TBL_PIISTEPTABLE_ETC          WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIORDER',                  COUNT(*) FROM COTDL.TBL_PIIORDER                  WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIORDERJOBWAIT',           COUNT(*) FROM COTDL.TBL_PIIORDERJOBWAIT           WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIORDERSTEP',              COUNT(*) FROM COTDL.TBL_PIIORDERSTEP              WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIORDERSTEPTABLE',         COUNT(*) FROM COTDL.TBL_PIIORDERSTEPTABLE         WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIORDERSTEPTABLEWAIT',     COUNT(*) FROM COTDL.TBL_PIIORDERSTEPTABLEWAIT     WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIORDERSTEPTABLEUPDATE',   COUNT(*) FROM COTDL.TBL_PIIORDERSTEPTABLEUPDATE   WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIORDERTHREAD',            COUNT(*) FROM COTDL.TBL_PIIORDERTHREAD            WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIAPPROVALREQ',            COUNT(*) FROM COTDL.TBL_PIIAPPROVALREQ            WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIRESTORE',                COUNT(*) FROM COTDL.TBL_PIIRESTORE                WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIRECOVERY',               COUNT(*) FROM COTDL.TBL_PIIRECOVERY               WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIEXTRACT',                COUNT(*) FROM COTDL.TBL_PIIEXTRACT                WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIEXTRACT_PURGE_STAT',     COUNT(*) FROM COTDL.TBL_PIIEXTRACT_PURGE_STAT     WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIEXTRACT_PURGE_LOG',      COUNT(*) FROM COTDL.TBL_PIIEXTRACT_PURGE_LOG      WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_TESTDATA',                  COUNT(*) FROM COTDL.TBL_TESTDATA                  WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
UNION ALL SELECT 'TBL_PIIUPLOAD_TEMPLATE',        COUNT(*) FROM COTDL.TBL_PIIUPLOAD_TEMPLATE        WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%' OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%';


-- ────────────────────────────────────────────────────────────
-- [B-1] LIKE — 실행본(YYYYMMDD 등)까지 함께 보고 싶을 때 개별 SELECT
--   필요한 테이블만 선택해서 실행하세요.
-- ────────────────────────────────────────────────────────────
-- SELECT * FROM COTDL.TBL_PIIJOB
--  WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%'
--     OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
--  ORDER BY JOBID;

-- SELECT * FROM COTDL.TBL_PIIORDER
--  WHERE JOBID LIKE 'PII_POLICY3_DAON_CORE_DELETE%'
--     OR JOBID LIKE 'PII_POLICY3_DAON_CORE_UPDATE%'
--  ORDER BY ORDERID DESC;
