-- ============================================================
-- JOB 설정 완전 삭제
-- 용도: 특정 JOBID의 모든 설정과 실행 이력을 완전히 삭제
-- 사용법: @JOBID 값을 변경 후, [1]사전확인 → [2]삭제 순서로 실행
-- ============================================================

-- ★ 대상 JOBID를 변경하세요
-- @JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208'


-- ============================================================
-- [1] 사전 확인 (삭제 전 잔존 데이터 확인)
-- ============================================================
SELECT 'TBL_PIIJOB'             AS TBL, COUNT(*) AS CNT FROM COTDL.TBL_PIIJOB             WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208'
UNION ALL SELECT 'TBL_PIISTEP',             COUNT(*) FROM COTDL.TBL_PIISTEP             WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208'
UNION ALL SELECT 'TBL_PIISTEPTABLE',        COUNT(*) FROM COTDL.TBL_PIISTEPTABLE        WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208'
UNION ALL SELECT 'TBL_PIISTEPTABLEUPDATE',  COUNT(*) FROM COTDL.TBL_PIISTEPTABLEUPDATE  WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208'
UNION ALL SELECT 'TBL_PIISTEPTABLEWAIT',    COUNT(*) FROM COTDL.TBL_PIISTEPTABLEWAIT    WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208'
UNION ALL SELECT 'TBL_PIIJOBWAIT',          COUNT(*) FROM COTDL.TBL_PIIJOBWAIT          WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208'
UNION ALL SELECT 'TBL_PIIORDER',            COUNT(*) FROM COTDL.TBL_PIIORDER            WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208'
UNION ALL SELECT 'TBL_PIIORDERSTEP',        COUNT(*) FROM COTDL.TBL_PIIORDERSTEP        WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208'
UNION ALL SELECT 'TBL_PIIORDERSTEPTABLE',   COUNT(*) FROM COTDL.TBL_PIIORDERSTEPTABLE   WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208'
UNION ALL SELECT 'TBL_PIIORDERJOBWAIT',     COUNT(*) FROM COTDL.TBL_PIIORDERJOBWAIT     WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208';


-- ============================================================
-- [2] 삭제 실행 (하위 테이블 → 상위 테이블 순서)
-- ============================================================

-- 실행 이력 (Order 관련)
DELETE FROM COTDL.TBL_PIIORDERSTEPTABLE WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208';
DELETE FROM COTDL.TBL_PIIORDERSTEP       WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208';
DELETE FROM COTDL.TBL_PIIORDERJOBWAIT    WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208';
DELETE FROM COTDL.TBL_PIIORDER           WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208';

-- Step 하위
DELETE FROM COTDL.TBL_PIISTEPTABLEUPDATE WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208';
DELETE FROM COTDL.TBL_PIISTEPTABLEWAIT   WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208';
DELETE FROM COTDL.TBL_PIISTEPTABLE       WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208';

-- Step
DELETE FROM COTDL.TBL_PIISTEP            WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208';

-- Job Wait
DELETE FROM COTDL.TBL_PIIJOBWAIT         WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208';

-- Job (메인)
DELETE FROM COTDL.TBL_PIIJOB             WHERE JOBID = 'PII_POLICY3_DAON_CORE_DELETE_20260208';

COMMIT;
