-- ============================================================
-- PATCH: DATA_LENGTH INT → BIGINT (PIITABLE + METATABLE 계열)
-- ============================================================
-- 원인: INFORMATION_SCHEMA.COLUMNS의 CHARACTER_MAXIMUM_LENGTH가
--       LONGTEXT/LONGBLOB에서 4294967295(4GB)를 반환하는데,
--       DATA_LENGTH가 INT(최대 2147483647)라서 오버플로우.
--
-- 적용 대상: DLM Home DB + 원천DB(DLMARC 등) 양쪽 모두
-- ============================================================

-- TBL_PIITABLE 계열
ALTER TABLE COTDL.TBL_PIITABLE     MODIFY COLUMN DATA_LENGTH BIGINT NULL;
ALTER TABLE COTDL.TBL_PIITABLE_TMP MODIFY COLUMN DATA_LENGTH BIGINT NULL;
ALTER TABLE COTDL.TBL_PIITABLE_NEW MODIFY COLUMN DATA_LENGTH BIGINT NULL;
ALTER TABLE COTDL.TBL_PIITABLE_OLD MODIFY COLUMN DATA_LENGTH BIGINT NULL;

-- TBL_METATABLE 계열
ALTER TABLE COTDL.TBL_METATABLE     MODIFY COLUMN DATA_LENGTH BIGINT NULL;
ALTER TABLE COTDL.TBL_METATABLE_TMP MODIFY COLUMN DATA_LENGTH BIGINT NULL;
ALTER TABLE COTDL.TBL_METATABLE_NEW MODIFY COLUMN DATA_LENGTH BIGINT NULL;
ALTER TABLE COTDL.TBL_METATABLE_OLD MODIFY COLUMN DATA_LENGTH BIGINT NULL;
