[Interface]
PrivateKey = uGXbBQ9yKpiEwGOwo8mfRujDSMnCb7sTGmfaEtv29HA=
Address = 10.8.234.5/24
DNS = 203.248.252.2

[Peer]
PublicKey = 0KnamtVVzZGLj4NGxc+hUtbv6xsmPoogeXvYTKz+inA=
# AllowedIPs = 0.0.0.0/0  # 원본 - 모든 트래픽 VPN
AllowedIPs = 10.8.234.0/24  # 한국손사 내부만 VPN
Endpoint = 106.242.169.2:51921
PresharedKey = mwbreZxp2dKKj9+AKVt5QJJDM0bfqzEXKGCOis4dbCc=