-- ============================================================
-- METATABLE 임시 테이블 재생성 (DROP & CREATE)
-- ============================================================
-- 적용 대상: 기존 운영 환경
-- 적용 날짜: 2026-03-30
-- 적용 순서: 이 파일 하나만 실행하면 됩니다.
--
-- [변경 내용]
-- 1. TBL_METATABLE_TMP  DROP & CREATE
-- 2. TBL_METATABLE_OLD  DROP & CREATE
-- 3. TBL_METATABLE_NEW  DROP & CREATE
--
-- [주의]
-- - 기존 테이블 데이터가 삭제됩니다. 임시 테이블이므로 데이터 보존 불필요.
-- ============================================================


-- ============================================================
-- 1. TBL_METATABLE_TMP
-- ============================================================
DROP TABLE IF EXISTS `COTDL`.`TBL_METATABLE_TMP`;
CREATE TABLE `COTDL`.`TBL_METATABLE_TMP` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_ID` INT NOT NULL,
  `PK_YN` VARCHAR(1),
  `PK_POSITION` INT,
  `FULL_DATA_TYPE` VARCHAR(100),
  `DATA_TYPE` VARCHAR(100) NOT NULL,
  `DATA_LENGTH` INT,
  `DOMAIN` VARCHAR(50),
  `PIITYPE` VARCHAR(50),
  `PIIGRADE` VARCHAR(10),
  `ENCRIPT_FLAG` VARCHAR(1),
  `SCRAMBLE_TYPE` VARCHAR(50),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  `MASTERKEY` VARCHAR(30),
  `MASTERYN` VARCHAR(1),
  `TABLE_COMMENT` VARCHAR(255),
  `COLUMN_COMMENT` VARCHAR(255),
  `VAL1` VARCHAR(100),
  `VAL2` VARCHAR(100),
  `VAL3` VARCHAR(100),
  `VAL4` VARCHAR(100),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- ============================================================
-- 2. TBL_METATABLE_NEW
-- ============================================================
DROP TABLE IF EXISTS `COTDL`.`TBL_METATABLE_NEW`;
CREATE TABLE `COTDL`.`TBL_METATABLE_NEW` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_ID` INT NOT NULL,
  `PK_YN` VARCHAR(1),
  `PK_POSITION` INT,
  `FULL_DATA_TYPE` VARCHAR(100),
  `DATA_TYPE` VARCHAR(100) NOT NULL,
  `DATA_LENGTH` INT,
  `DOMAIN` VARCHAR(50),
  `PIITYPE` VARCHAR(50),
  `PIIGRADE` VARCHAR(10),
  `ENCRIPT_FLAG` VARCHAR(1),
  `SCRAMBLE_TYPE` VARCHAR(50),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  `MASTERKEY` VARCHAR(30),
  `MASTERYN` VARCHAR(1),
  `TABLE_COMMENT` VARCHAR(255),
  `COLUMN_COMMENT` VARCHAR(255),
  `VAL1` VARCHAR(100),
  `VAL2` VARCHAR(100),
  `VAL3` VARCHAR(100),
  `VAL4` VARCHAR(100),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- ============================================================
-- 3. TBL_METATABLE_OLD
-- ============================================================
DROP TABLE IF EXISTS `COTDL`.`TBL_METATABLE_OLD`;
CREATE TABLE `COTDL`.`TBL_METATABLE_OLD` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_ID` INT NOT NULL,
  `PK_YN` VARCHAR(1),
  `PK_POSITION` INT,
  `FULL_DATA_TYPE` VARCHAR(100),
  `DATA_TYPE` VARCHAR(100) NOT NULL,
  `DATA_LENGTH` INT,
  `DOMAIN` VARCHAR(50),
  `PIITYPE` VARCHAR(50),
  `PIIGRADE` VARCHAR(10),
  `ENCRIPT_FLAG` VARCHAR(1),
  `SCRAMBLE_TYPE` VARCHAR(50),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  `MASTERKEY` VARCHAR(30),
  `MASTERYN` VARCHAR(1),
  `TABLE_COMMENT` VARCHAR(255),
  `COLUMN_COMMENT` VARCHAR(255),
  `VAL1` VARCHAR(100),
  `VAL2` VARCHAR(100),
  `VAL3` VARCHAR(100),
  `VAL4` VARCHAR(100),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
