-- ============================================================
-- DLM_BATCH_MEMBER : 사용자 정보 동기화 배치 잡
-- ============================================================
-- 원천 시스템(인사/조직 DB)의 사용자 정보를 추출하여
-- DLM 관리 DB의 TBL_MEMBER 테이블에 동기화(INSERT/UPDATE/DELETE)하는
-- 배치 잡 등록 스크립트.
--
-- [동기화 대상 컬럼]
--   USERID, USERNAME, DEPT_CD, DEPT_NAME, TELNO, GRADE,
--   EMAIL, MANAGER_ID, POSITION
--   * USERPW, ENABLED, REGDATE, UPDATEDATE 는 동기화 제외 (DLM 자체 관리)
--
-- [배치 흐름]
--   Step1 EXTRACT_MEMBER : 원천DB에서 사용자 추출 -> TMP/NEW/OLD 비교 -> 반영
--   Step2 EXE_HOMECAST   : NEW/OLD 임시 테이블을 Home DB(DLM)로 전송
--   Step3 EXE_FINISH     : Home DB에 최종 반영 + 임시 테이블 정리
--
-- [TMP/NEW/OLD 비교 로직]
--   TBL_MEMBER_TMP : 원천에서 추출한 전체 사용자 (스냅샷)
--   TBL_MEMBER_NEW : TMP에 있고 기존에 없거나 변경된 레코드 (INSERT/UPDATE 대상)
--   TBL_MEMBER_OLD : 기존에 있고 TMP에 없거나 변경된 레코드 (DELETE/UPDATE 대상)
--
--   변경 감지 비교 키: USERID(PK), USERNAME, DEPT_CD, DEPT_NAME,
--                      TELNO, EMAIL, MANAGER_ID, POSITION
--   * GRADE는 변경 감지 제외 (DLM 자체 관리)
--
-- ============================================================
-- 사이트별 배포 시 아래 변수를 해당 사이트 값으로 치환(Replace All)하세요.
--
--   DLM_BATCH_MEMBER          -> 잡 ID                            (기본값: DLM_BATCH_MEMBER)
--   DLM        -> DLM Home DB명                    (기본값: DLM)
--   COTDL     -> DLM 스키마명                     (기본값: COTDL)
--   DAON      -> 원천 DB명 (인사/조직 시스템 DB)   (예: DAON)
--   COOWNSER  -> 원천 스키마명                    (예: COOWNSER)
--   TB_HR_USER_INFO   -> 원천 사용자 테이블명             (예: TB_HR_USER_INFO)
--   07:20     -> 실행 시각 (HH:MM)                (기본값: 07:20)
--   admin     -> 등록/수정 사용자 ID               (기본값: admin)
--
-- [원천 테이블 매핑 예시]
--   원천 테이블의 컬럼명이 다를 경우 Step1의 4-1-1 추출 SQL을 사이트에 맞게 수정하세요.
--   예) TB_USER_INFO.EMP_NO → USERID, TB_USER_INFO.EMP_NM → USERNAME 등
-- ============================================================


-- 1. 기존 잡 정의 삭제
DELETE FROM COTDL.TBL_PIIJOB       WHERE JOBID = 'DLM_BATCH_MEMBER';
DELETE FROM COTDL.TBL_PIISTEP      WHERE JOBID = 'DLM_BATCH_MEMBER';
DELETE FROM COTDL.TBL_PIISTEPTABLE WHERE JOBID = 'DLM_BATCH_MEMBER';


-- ============================================================
-- 2. JOB 등록
-- ============================================================
INSERT INTO COTDL.TBL_PIIJOB (
    JOBID, VERSION, JOBNAME, `SYSTEM`, POLICY_ID, KEYMAP_ID,
    JOBTYPE, RUNTYPE, CALENDAR, `TIME`, CRONVAL, CONFIRMFLAG, STATUS, PHASE,
    JOB_OWNER_ID1, JOB_OWNER_NAME1,
    JOB_OWNER_ID2, JOB_OWNER_NAME2,
    JOB_OWNER_ID3, JOB_OWNER_NAME3,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'DLM_BATCH_MEMBER_사용자정보_동기화', NULL, NULL, NULL,
    'BATCH', 'DLM_BATCH', 'ALLDAYS', '07:20', '##########', 'N', 'ACTIVE', 'CHECKIN',
    'admin', 'admin',
    NULL, NULL,
    NULL, NULL,
    NULL, NOW(), NOW(), 'admin', 'admin'
);


-- ============================================================
-- 3. STEP 등록 (3단계)
-- ============================================================

-- Step1: 원천DB에서 사용자 정보 추출 + TMP/NEW/OLD 비교
INSERT INTO COTDL.TBL_PIISTEP (
    JOBID, VERSION, STEPID, STEPNAME, STEPTYPE, STEPSEQ, DB,
    STATUS, PHASE, THREADCNT, COMMITCNT,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXTRACT_MEMBER', 'MEMBER_EXTRACT', 'EXE_EXTRACT', 1, 'DAON',
    'ACTIVE', 'CHECKOUT', 1, 5000,
    NULL, NOW(), NOW(), 'admin', 'admin'
);

-- Step2: 임시 테이블을 Home DB로 전송
INSERT INTO COTDL.TBL_PIISTEP (
    JOBID, VERSION, STEPID, STEPNAME, STEPTYPE, STEPSEQ, DB,
    STATUS, PHASE, THREADCNT, COMMITCNT,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXE_HOMECAST', 'MEMBER_HOMECAST', 'EXE_HOMECAST', 2, 'DAON',
    'ACTIVE', 'CHECKOUT', 10, 5000,
    NULL, NOW(), NOW(), 'admin', 'admin'
);

-- Step3: Home DB 최종 반영 + 정리
INSERT INTO COTDL.TBL_PIISTEP (
    JOBID, VERSION, STEPID, STEPNAME, STEPTYPE, STEPSEQ, DB,
    STATUS, PHASE, THREADCNT, COMMITCNT,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXE_FINISH', 'MEMBER_FINISH', 'EXE_FINISH', 3, 'DAON',
    'ACTIVE', 'CHECKOUT', 1, 5000,
    NULL, NOW(), NOW(), 'admin', 'admin'
);


-- ============================================================
-- 4. STEPTABLE 등록
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- Step1: EXTRACT_MEMBER (원천DB에서 실행)
-- ────────────────────────────────────────────────────────────

-- 4-1-0. [SEQ 50] TBL_MEMBER_TMP 초기화
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXTRACT_MEMBER', 'DAON', 'COTDL', 'TBL_MEMBER_TMP',
    NULL, 'ETC', 'EXTRACT', '', '', NULL, NULL,
    10, 50, 10, NULL,
    'TBL_MEMBER_TMP 초기화', '', '', NULL, NULL,
    NULL, 'DELETE FROM COTDL.TBL_MEMBER_TMP',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-1-1. [SEQ 100] 원천 사용자 테이블 → TBL_MEMBER_TMP 추출
--   ★ 사이트별로 원천 테이블/컬럼명을 맞춰 수정하세요 ★
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXTRACT_MEMBER', 'DAON', 'COTDL', 'TBL_MEMBER_TMP',
    NULL, 'ADD', 'EXTRACT', '', '', NULL, NULL,
    10, 100, 10, NULL,
    '원천 사용자 정보 추출', '', '', NULL, NULL,
    NULL,
'INSERT INTO COTDL.TBL_MEMBER_TMP
       (USERID, USERPW, USERNAME, REGDATE, UPDATEDATE, ENABLED,
        DEPT_CD, DEPT_NAME, TELNO, GRADE, EMAIL, MANAGER_ID, POSITION)
SELECT EMP_NO                          AS USERID
     , ''__SKIP__''                    AS USERPW
     , EMP_NM                          AS USERNAME
     , SYSDATE                         AS REGDATE
     , SYSDATE                         AS UPDATEDATE
     , CASE WHEN USE_YN = ''Y'' THEN ''1'' ELSE ''0'' END AS ENABLED
     , DEPT_CD                         AS DEPT_CD
     , DEPT_NM                         AS DEPT_NAME
     , COALESCE(TEL_NO, '''')          AS TELNO
     , COALESCE(GRADE_NM, '''')        AS GRADE
     , COALESCE(EMAIL, '''')           AS EMAIL
     , COALESCE(MGR_EMP_NO, '''')      AS MANAGER_ID
     , COALESCE(POSITION_NM, '''')     AS POSITION
  FROM COOWNSER.TB_HR_USER_INFO
 WHERE USE_YN = ''Y''',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-1-2. [SEQ 150] TBL_MEMBER_NEW 초기화
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXTRACT_MEMBER', 'DAON', 'COTDL', 'TBL_MEMBER_NEW',
    NULL, 'ETC', 'EXTRACT', '', '', NULL, NULL,
    10, 150, 10, NULL,
    'TBL_MEMBER_NEW 초기화', '', '', NULL, NULL,
    NULL, 'DELETE FROM COTDL.TBL_MEMBER_NEW',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-1-3. [SEQ 160] TBL_MEMBER_OLD 초기화
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXTRACT_MEMBER', 'DAON', 'COTDL', 'TBL_MEMBER_OLD',
    NULL, 'ETC', 'EXTRACT', '', '', NULL, NULL,
    10, 160, 10, NULL,
    'TBL_MEMBER_OLD 초기화', '', '', NULL, NULL,
    NULL, 'DELETE FROM COTDL.TBL_MEMBER_OLD',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-1-4. [SEQ 200] TBL_MEMBER_NEW 추출 (신규/변경 사용자 = TMP에 있고 기존에 없거나 다른 것)
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXTRACT_MEMBER', 'DAON', 'COTDL', 'TBL_MEMBER_NEW',
    NULL, 'ADD', 'EXTRACT', '', '', NULL, NULL,
    10, 200, 10, NULL,
    '신규/변경 사용자 추출', '', '', NULL, NULL,
    NULL,
'INSERT INTO COTDL.TBL_MEMBER_NEW
SELECT t.* FROM COTDL.TBL_MEMBER_TMP t
WHERE NOT EXISTS (
    SELECT 1 FROM COTDL.TBL_MEMBER e
    WHERE e.USERID    = t.USERID
      AND COALESCE(e.USERNAME, '''')   = COALESCE(t.USERNAME, '''')
      AND COALESCE(e.DEPT_CD, '''')    = COALESCE(t.DEPT_CD, '''')
      AND COALESCE(e.DEPT_NAME, '''')  = COALESCE(t.DEPT_NAME, '''')
      AND COALESCE(e.TELNO, '''')      = COALESCE(t.TELNO, '''')
      AND COALESCE(e.EMAIL, '''')      = COALESCE(t.EMAIL, '''')
      AND COALESCE(e.MANAGER_ID, '''') = COALESCE(t.MANAGER_ID, '''')
      AND COALESCE(e.POSITION, '''')   = COALESCE(t.POSITION, '''')
)',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-1-5. [SEQ 300] TBL_MEMBER_OLD 추출 (삭제/변경 사용자 = 기존에 있고 TMP에 없거나 다른 것)
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXTRACT_MEMBER', 'DAON', 'COTDL', 'TBL_MEMBER_OLD',
    NULL, 'ADD', 'EXTRACT', '', '', NULL, NULL,
    10, 300, 10, NULL,
    '삭제/변경 사용자 추출', '', '', NULL, NULL,
    NULL,
'INSERT INTO COTDL.TBL_MEMBER_OLD
SELECT e.* FROM COTDL.TBL_MEMBER e
WHERE e.USERID != ''admin''
  AND NOT EXISTS (
    SELECT 1 FROM COTDL.TBL_MEMBER_TMP t
    WHERE t.USERID    = e.USERID
      AND COALESCE(t.USERNAME, '''')   = COALESCE(e.USERNAME, '''')
      AND COALESCE(t.DEPT_CD, '''')    = COALESCE(e.DEPT_CD, '''')
      AND COALESCE(t.DEPT_NAME, '''')  = COALESCE(e.DEPT_NAME, '''')
      AND COALESCE(t.TELNO, '''')      = COALESCE(e.TELNO, '''')
      AND COALESCE(t.GRADE, '''')      = COALESCE(e.GRADE, '''')
      AND COALESCE(t.EMAIL, '''')      = COALESCE(e.EMAIL, '''')
      AND COALESCE(t.MANAGER_ID, '''') = COALESCE(e.MANAGER_ID, '''')
      AND COALESCE(t.POSITION, '''')   = COALESCE(e.POSITION, '''')
)',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-1-6. [SEQ 400] 변경/삭제 사용자를 TBL_MEMBER에서 제거
--   admin 계정은 보호 (삭제 대상 제외)
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXTRACT_MEMBER', 'DAON', 'COTDL', 'TBL_MEMBER',
    NULL, 'EXCLUDE', 'EXTRACT', '', '', NULL, NULL,
    10, 400, 10, NULL,
    '변경/삭제 사용자 제거', '', '', NULL, NULL,
    NULL,
'DELETE FROM COTDL.TBL_MEMBER
WHERE USERID != ''admin''
  AND EXISTS (
    SELECT 1 FROM COTDL.TBL_MEMBER_OLD o
    WHERE o.USERID = COTDL.TBL_MEMBER.USERID
)',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-1-7. [SEQ 500] 신규/변경 사용자를 TBL_MEMBER에 반영
--   USERPW 처리: 신규 사용자는 초기 비밀번호(#USERID), 기존 사용자는 기존 비밀번호 유지
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXTRACT_MEMBER', 'DAON', 'COTDL', 'TBL_MEMBER',
    NULL, 'ADD', 'EXTRACT', '', '', NULL, NULL,
    10, 500, 10, NULL,
    '신규/변경 사용자 반영', '', '', NULL, NULL,
    NULL,
'INSERT INTO COTDL.TBL_MEMBER
       (USERID, USERPW, USERNAME, REGDATE, UPDATEDATE, ENABLED,
        DEPT_CD, DEPT_NAME, TELNO, GRADE, EMAIL, MANAGER_ID, POSITION)
SELECT n.USERID
     , COALESCE(o.USERPW, CONCAT(''#'', n.USERID))
     , n.USERNAME
     , COALESCE(o.REGDATE, SYSDATE)
     , SYSDATE
     , COALESCE(o.ENABLED, ''1'')
     , n.DEPT_CD
     , n.DEPT_NAME
     , n.TELNO
     , n.GRADE
     , n.EMAIL
     , n.MANAGER_ID
     , n.POSITION
  FROM COTDL.TBL_MEMBER_NEW n
  LEFT JOIN COTDL.TBL_MEMBER_OLD o ON o.USERID = n.USERID',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), 'admin', 'admin'
);


-- ────────────────────────────────────────────────────────────
-- Step2: EXE_HOMECAST (원천DB -> Home DB 전송)
-- ────────────────────────────────────────────────────────────

-- 4-2-1. [SEQ 100] TBL_MEMBER_NEW를 Home DB로 전송
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXE_HOMECAST', 'DAON', 'COTDL', 'TBL_MEMBER_NEW',
    NULL, NULL, 'HOMECAST', '', '', NULL, NULL,
    10, 100, 10, NULL,
    '', '', '', NULL, NULL,
    ' ',
'INSERT INTO COTDL.TBL_MEMBER_NEW
SELECT * FROM COTDL.TBL_MEMBER_NEW',
    NULL, NULL, NULL, '', 'AUTO',
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-2-2. [SEQ 200] TBL_MEMBER_OLD를 Home DB로 전송
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXE_HOMECAST', 'DAON', 'COTDL', 'TBL_MEMBER_OLD',
    NULL, NULL, 'HOMECAST', '', '', NULL, NULL,
    10, 200, 10, NULL,
    '', '', '', NULL, NULL,
    ' ',
'INSERT INTO COTDL.TBL_MEMBER_OLD
SELECT * FROM COTDL.TBL_MEMBER_OLD',
    NULL, NULL, NULL, '', 'AUTO',
    NOW(), NOW(), 'admin', 'admin'
);


-- ────────────────────────────────────────────────────────────
-- Step3: EXE_FINISH (정리 + Home DB 최종 반영)
-- ────────────────────────────────────────────────────────────

-- 4-3-1. [SEQ 100] 원천DB TBL_MEMBER_TMP 정리
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXE_FINISH', 'DAON', 'COTDL', 'TBL_MEMBER_TMP',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    10, 100, 10, NULL,
    '', '', '', NULL, NULL,
    ' ',
'DELETE FROM COTDL.TBL_MEMBER_TMP',
    NULL, NULL, NULL, '', 'AUTO',
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-3-2. [SEQ 200] 원천DB TBL_MEMBER_NEW 정리
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXE_FINISH', 'DAON', 'COTDL', 'TBL_MEMBER_NEW',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    10, 200, 10, NULL,
    '', '', '', NULL, NULL,
    ' ',
'DELETE FROM COTDL.TBL_MEMBER_NEW',
    NULL, NULL, NULL, '', 'AUTO',
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-3-3. [SEQ 300] 원천DB TBL_MEMBER_OLD 정리
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXE_FINISH', 'DAON', 'COTDL', 'TBL_MEMBER_OLD',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    10, 300, 10, NULL,
    '', '', '', NULL, NULL,
    ' ',
'DELETE FROM COTDL.TBL_MEMBER_OLD',
    NULL, NULL, NULL, '', 'AUTO',
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-3-4. [SEQ 400] Home DB: 변경/삭제 사용자를 TBL_MEMBER에서 제거 (admin 보호)
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXE_FINISH', 'DLM', 'COTDL', 'TBL_MEMBER',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    10, 400, 10, NULL,
    '', '', '', NULL, NULL,
    ' ',
'DELETE FROM COTDL.TBL_MEMBER
WHERE USERID != ''admin''
  AND EXISTS (
    SELECT 1 FROM COTDL.TBL_MEMBER_OLD o
    WHERE o.USERID = COTDL.TBL_MEMBER.USERID
)',
    NULL, NULL, NULL, '', 'AUTO',
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-3-5. [SEQ 500] Home DB: 신규/변경 사용자를 TBL_MEMBER에 반영
--   기존 비밀번호/활성화 상태/등록일은 OLD에서 보존, 신규는 초기값 사용
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXE_FINISH', 'DLM', 'COTDL', 'TBL_MEMBER',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    10, 500, 10, NULL,
    '', '', '', NULL, NULL,
    ' ',
'INSERT INTO COTDL.TBL_MEMBER
       (USERID, USERPW, USERNAME, REGDATE, UPDATEDATE, ENABLED,
        DEPT_CD, DEPT_NAME, TELNO, GRADE, EMAIL, MANAGER_ID, POSITION)
SELECT n.USERID
     , COALESCE(o.USERPW, CONCAT(''#'', n.USERID))
     , n.USERNAME
     , COALESCE(o.REGDATE, NOW())
     , NOW()
     , COALESCE(o.ENABLED, ''1'')
     , n.DEPT_CD
     , n.DEPT_NAME
     , n.TELNO
     , n.GRADE
     , n.EMAIL
     , n.MANAGER_ID
     , n.POSITION
  FROM COTDL.TBL_MEMBER_NEW n
  LEFT JOIN COTDL.TBL_MEMBER_OLD o ON o.USERID = n.USERID',
    NULL, NULL, NULL, '', 'AUTO',
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-3-5a. [SEQ 510] Home DB: 삭제된 사용자의 권한 제거
--   OLD에 있고 NEW에 없는 사용자 = 진짜 삭제된 사용자
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXE_FINISH', 'DLM', 'COTDL', 'TBL_MEMBER_AUTH',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    10, 510, 10, NULL,
    '', '', '', NULL, NULL,
    ' ',
'DELETE FROM COTDL.TBL_MEMBER_AUTH
WHERE USERID != ''admin''
  AND EXISTS (
    SELECT 1 FROM COTDL.TBL_MEMBER_OLD o
    WHERE o.USERID = COTDL.TBL_MEMBER_AUTH.USERID
      AND NOT EXISTS (
        SELECT 1 FROM COTDL.TBL_MEMBER_NEW n
        WHERE n.USERID = o.USERID
      )
)',
    NULL, NULL, NULL, '', 'AUTO',
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-3-5b. [SEQ 520] Home DB: 신규 사용자에 ROLE_USER 권한 부여
--   NEW에 있고 OLD에 없는 사용자 = 진짜 신규 사용자
--   이미 TBL_MEMBER_AUTH에 존재하는 경우는 건너뜀
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXE_FINISH', 'DLM', 'COTDL', 'TBL_MEMBER_AUTH',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    10, 520, 10, NULL,
    '', '', '', NULL, NULL,
    ' ',
'INSERT INTO COTDL.TBL_MEMBER_AUTH (USERID, AUTH)
SELECT n.USERID, ''ROLE_USER''
  FROM COTDL.TBL_MEMBER_NEW n
 WHERE NOT EXISTS (
    SELECT 1 FROM COTDL.TBL_MEMBER_OLD o
    WHERE o.USERID = n.USERID
 )
   AND NOT EXISTS (
    SELECT 1 FROM COTDL.TBL_MEMBER_AUTH a
    WHERE a.USERID = n.USERID
 )',
    NULL, NULL, NULL, '', 'AUTO',
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-3-6. [SEQ 600] Home DB: TBL_MEMBER_NEW 정리
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXE_FINISH', 'DLM', 'COTDL', 'TBL_MEMBER_NEW',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    10, 600, 10, NULL,
    '', '', '', NULL, NULL,
    ' ',
'DELETE FROM COTDL.TBL_MEMBER_NEW',
    NULL, NULL, NULL, '', 'AUTO',
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-3-7. [SEQ 700] Home DB: TBL_MEMBER_OLD 정리
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_MEMBER', '1', 'EXE_FINISH', 'DLM', 'COTDL', 'TBL_MEMBER_OLD',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    10, 700, 10, NULL,
    '', '', '', NULL, NULL,
    ' ',
'DELETE FROM COTDL.TBL_MEMBER_OLD',
    NULL, NULL, NULL, '', 'AUTO',
    NOW(), NOW(), 'admin', 'admin'
);


COMMIT;
