-- ============================================================
-- X-Audit EXTERNAL 모드 — 고객사 별도 PostgreSQL 배포 스키마 (V1)
-- 2026-04-27 신규
--
-- 용도: XAUDIT_STORAGE_MODE=EXTERNAL 일 때 고객사 감사 DB 에 1회 실행.
-- 구조: Master Fact Table + 1:1 Sidecar (MariaDB/Oracle 버전과 1:1 동형)
--       + 월별 RANGE 파티셔닝 (access_time 기준)
-- 실행 주체: 해당 스키마 소유 유저 (예: xaudit / click_audit)
--
-- 지원 버전:
--   · PostgreSQL 14+   — ✅ 권장 (선언적 파티셔닝 + IDENTITY 안정)
--   · PostgreSQL 11~13 — 선언적 파티셔닝 + IDENTITY 지원
--   · PostgreSQL 10    — 선언적 파티셔닝 1세대 (운영 시 14+ 권장)
--   · PostgreSQL 9.x   — 미지원 (상속 기반 파티셔닝 별도 작업 필요)
--
-- ⚠️ PostgreSQL 은 Oracle INTERVAL 같은 자동 파티션 생성을 기본 미지원.
--    아래 9개월치 사전 생성 + 매월 1일 신월 파티션 추가 필요.
--    자동화 권장: pg_partman 확장 (https://github.com/pgpartman/pg_partman)
--      → 아래 [pg_partman 운영 모드] 블록 참조
--
-- 실행:
--   psql -h <host> -U <xaudit_user> -d <xaudit_db> -f XAUDIT_SCHEMA_POSTGRESQL.sql
--
-- TBL_PIIDATABASE 등록 규약:
--   db='XAUDIT_DB', system='XAUDIT', dbtype='POSTGRESQL', …
--   DLM .env: XAUDIT_STORAGE_MODE=EXTERNAL   (db-key default=XAUDIT_DB)
-- ============================================================

-- 1) Master — TBL_ACCESS_LOG (월 RANGE 파티션)
DROP TABLE IF EXISTS TBL_ACCESS_LOG CASCADE;
CREATE TABLE TBL_ACCESS_LOG (
    log_id             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    -- WHO
    source_system_id   VARCHAR(36),
    user_account       VARCHAR(100),
    user_name          VARCHAR(100),
    department         VARCHAR(100),
    -- WHEN
    access_time        TIMESTAMP(3)  NOT NULL,
    -- WHERE
    client_ip          VARCHAR(45),
    session_id         VARCHAR(100),
    -- WHAT
    action_type        VARCHAR(20)   NOT NULL,
    target_db          VARCHAR(100),
    target_schema      VARCHAR(100),
    target_table       VARCHAR(200),
    affected_rows      INTEGER       DEFAULT 0,
    result_code        VARCHAR(10)   DEFAULT 'SUCCESS',
    -- PII
    pii_type_codes     VARCHAR(200),
    pii_grade          CHAR(1),
    pii_detected_flag  CHAR(1)       DEFAULT 'N',
    -- 수집 메타
    collect_type       VARCHAR(20),
    access_channel     VARCHAR(20)   DEFAULT 'WAS',
    -- 무결성
    hash_value         VARCHAR(64),
    prev_hash          VARCHAR(64),
    collected_at       TIMESTAMP(3)  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    partition_key      VARCHAR(8),
    -- WAS HTTP 컨텍스트
    req_id             VARCHAR(36),
    service_name       VARCHAR(50),
    menu_id            VARCHAR(100),
    uri                VARCHAR(500),
    http_method        VARCHAR(10),
    http_status        INTEGER,
    duration_ms        BIGINT,
    CONSTRAINT pk_access_log PRIMARY KEY (log_id, access_time)
)
PARTITION BY RANGE (access_time);

-- 월별 파티션 사전 생성 (9개월치 + DEFAULT)
CREATE TABLE TBL_ACCESS_LOG_p202601 PARTITION OF TBL_ACCESS_LOG FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE TBL_ACCESS_LOG_p202602 PARTITION OF TBL_ACCESS_LOG FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE TBL_ACCESS_LOG_p202603 PARTITION OF TBL_ACCESS_LOG FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE TBL_ACCESS_LOG_p202604 PARTITION OF TBL_ACCESS_LOG FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE TBL_ACCESS_LOG_p202605 PARTITION OF TBL_ACCESS_LOG FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE TBL_ACCESS_LOG_p202606 PARTITION OF TBL_ACCESS_LOG FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE TBL_ACCESS_LOG_p202607 PARTITION OF TBL_ACCESS_LOG FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE TBL_ACCESS_LOG_p202608 PARTITION OF TBL_ACCESS_LOG FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE TBL_ACCESS_LOG_p202609 PARTITION OF TBL_ACCESS_LOG FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE TBL_ACCESS_LOG_pdefault PARTITION OF TBL_ACCESS_LOG DEFAULT;

COMMENT ON TABLE  TBL_ACCESS_LOG                    IS 'X-Audit 접속기록 Master (월 RANGE 파티션)';
COMMENT ON COLUMN TBL_ACCESS_LOG.hash_value         IS 'SHA-256 해시 (위변조 방지, 안전성확보조치 8조 3항)';
COMMENT ON COLUMN TBL_ACCESS_LOG.partition_key      IS 'YYYYMMDD — 월 파티션 키 (보조)';
COMMENT ON COLUMN TBL_ACCESS_LOG.pii_detected_flag  IS 'Y/N — PII 포함 빠른 필터';

-- 인덱스 (partitioned table 에 생성하면 모든 파티션에 자동 전파됨, PG 11+)
CREATE INDEX idx_al_access_time  ON TBL_ACCESS_LOG (access_time);
CREATE INDEX idx_al_user_account ON TBL_ACCESS_LOG (user_account, access_time);
CREATE INDEX idx_al_action_type  ON TBL_ACCESS_LOG (action_type, access_time);
CREATE INDEX idx_al_pii_flag     ON TBL_ACCESS_LOG (pii_detected_flag, access_time);
CREATE INDEX idx_al_pii_grade    ON TBL_ACCESS_LOG (pii_grade, access_time);
CREATE INDEX idx_al_target_table ON TBL_ACCESS_LOG (target_table, access_time);
CREATE INDEX idx_al_collect_type ON TBL_ACCESS_LOG (collect_type, access_time);
CREATE INDEX idx_al_req_id       ON TBL_ACCESS_LOG (req_id);
CREATE INDEX idx_al_service      ON TBL_ACCESS_LOG (service_name, access_time);
CREATE INDEX idx_al_hash         ON TBL_ACCESS_LOG (hash_value);

-- 2) Sidecar — TBL_ACCESS_LOG_DETAIL (월 RANGE 파티션)
DROP TABLE IF EXISTS TBL_ACCESS_LOG_DETAIL CASCADE;
CREATE TABLE TBL_ACCESS_LOG_DETAIL (
    log_id           BIGINT        NOT NULL,
    access_time      TIMESTAMP(3)  NOT NULL,
    req_id           VARCHAR(36),
    sql_id           VARCHAR(255),
    sql_text         TEXT,
    bind_params      TEXT,
    search_condition VARCHAR(4000),
    target_columns   VARCHAR(4000),
    full_uri         VARCHAR(2000),
    user_agent       VARCHAR(500),
    error_message    VARCHAR(500),
    collected_at     TIMESTAMP(3)  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_access_log_detail PRIMARY KEY (log_id, access_time)
)
PARTITION BY RANGE (access_time);

CREATE TABLE TBL_ACCESS_LOG_DETAIL_p202601 PARTITION OF TBL_ACCESS_LOG_DETAIL FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE TBL_ACCESS_LOG_DETAIL_p202602 PARTITION OF TBL_ACCESS_LOG_DETAIL FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE TBL_ACCESS_LOG_DETAIL_p202603 PARTITION OF TBL_ACCESS_LOG_DETAIL FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE TBL_ACCESS_LOG_DETAIL_p202604 PARTITION OF TBL_ACCESS_LOG_DETAIL FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE TBL_ACCESS_LOG_DETAIL_p202605 PARTITION OF TBL_ACCESS_LOG_DETAIL FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE TBL_ACCESS_LOG_DETAIL_p202606 PARTITION OF TBL_ACCESS_LOG_DETAIL FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE TBL_ACCESS_LOG_DETAIL_p202607 PARTITION OF TBL_ACCESS_LOG_DETAIL FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE TBL_ACCESS_LOG_DETAIL_p202608 PARTITION OF TBL_ACCESS_LOG_DETAIL FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE TBL_ACCESS_LOG_DETAIL_p202609 PARTITION OF TBL_ACCESS_LOG_DETAIL FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE TBL_ACCESS_LOG_DETAIL_pdefault PARTITION OF TBL_ACCESS_LOG_DETAIL DEFAULT;

COMMENT ON TABLE  TBL_ACCESS_LOG_DETAIL          IS 'X-Audit 접속기록 상세 sidecar (월 RANGE 파티션)';
COMMENT ON COLUMN TBL_ACCESS_LOG_DETAIL.sql_text IS 'SQL 풀 원문 (전자금융 13조9항 대응)';

CREATE INDEX idx_ald_req  ON TBL_ACCESS_LOG_DETAIL (req_id);
CREATE INDEX idx_ald_time ON TBL_ACCESS_LOG_DETAIL (access_time);

-- 3) 통합 조회 뷰
DROP VIEW IF EXISTS V_ACCESS_LOG_UNIFIED;
CREATE VIEW V_ACCESS_LOG_UNIFIED AS
SELECT
    a.log_id, a.source_system_id, a.user_account, a.user_name, a.department,
    a.access_time, a.client_ip, a.session_id,
    a.action_type, a.target_db, a.target_schema, a.target_table,
    a.affected_rows, a.result_code,
    a.pii_type_codes, a.pii_grade, a.pii_detected_flag,
    a.collect_type, a.access_channel,
    a.hash_value, a.prev_hash, a.collected_at, a.partition_key,
    a.req_id, a.service_name, a.menu_id, a.uri, a.http_method,
    a.http_status, a.duration_ms,
    d.sql_id, d.sql_text, d.bind_params, d.search_condition,
    d.target_columns, d.full_uri, d.user_agent, d.error_message
FROM TBL_ACCESS_LOG a
LEFT JOIN TBL_ACCESS_LOG_DETAIL d
       ON a.log_id = d.log_id AND a.access_time = d.access_time;

-- 4) Verification
\echo 'XAUDIT External Schema (PostgreSQL) deployed'
\dt TBL_ACCESS_LOG*


-- ============================================================
-- 운영 가이드 — 월 파티션 수동 관리
-- ============================================================
-- · 매월 신월 파티션 추가 (cron / pg_cron 으로 자동화 권장):
--     CREATE TABLE TBL_ACCESS_LOG_p202610
--       PARTITION OF TBL_ACCESS_LOG
--       FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
--     CREATE TABLE TBL_ACCESS_LOG_DETAIL_p202610
--       PARTITION OF TBL_ACCESS_LOG_DETAIL
--       FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
--
-- · 파티션 목록 조회:
--     SELECT inhrelid::regclass FROM pg_inherits
--      WHERE inhparent = 'tbl_access_log'::regclass
--      ORDER BY 1;
--
-- · 보유기간 초과 파티션 삭제 (예: 2년 이전):
--     ALTER TABLE TBL_ACCESS_LOG DETACH PARTITION TBL_ACCESS_LOG_p202401;
--     DROP TABLE TBL_ACCESS_LOG_p202401;
--   (또는 한 번에: DROP TABLE TBL_ACCESS_LOG_p202401;)
--   → 인덱스도 함께 자동 정리됨
--
-- · DLM AccessLogArchiveScheduler 가 RETENTION_PERIOD_YEARS 설정에 따라 자동 호출
--   (PostgreSQL 어댑터는 ALTER TABLE ... DETACH + DROP TABLE 호출 필요 — 확인 필수)


-- ============================================================
-- [pg_partman 운영 모드] 매월 파티션 추가를 자동화하려면
-- 위 9개월치 CREATE TABLE 블록 대신 아래 사용:
-- ============================================================
-- CREATE EXTENSION IF NOT EXISTS pg_partman;
--
-- SELECT partman.create_parent(
--     p_parent_table := 'public.tbl_access_log',
--     p_control      := 'access_time',
--     p_type         := 'native',
--     p_interval     := '1 month',
--     p_start_partition := '2026-01-01'
-- );
-- SELECT partman.create_parent(
--     p_parent_table := 'public.tbl_access_log_detail',
--     p_control      := 'access_time',
--     p_type         := 'native',
--     p_interval     := '1 month',
--     p_start_partition := '2026-01-01'
-- );
--
-- -- pg_cron + run_maintenance() 로 매일 자정 신월 파티션 생성:
-- SELECT cron.schedule('partman-maintenance', '0 0 * * *',
--                      $$SELECT partman.run_maintenance();$$);
