-- ============================================================
-- DLM_BATCH_METADATA_UPDATE : TBL_METATABLE 일일 갱신 배치 잡
-- ============================================================
-- 사이트별 배포 시 아래 변수를 해당 사이트 값으로 치환(Replace All)하세요.
--
--   #{JOBID}            -> 잡 ID              (기본값: DLM_BATCH_METADATA_UPDATE)
--   #{DLM_DB}           -> DLM 관리 DB명       (기본값: DLM)
--   #{DLM_SCHEMA}       -> DLM 스키마명        (기본값: COTDL)
--   #{TARGET_DB_LIST}   -> 대상 DB 목록        (예: ''DAON'',''DW'')
--   #{EXCLUDE_OWNER}    -> 제외할 OWNER        (기본값: COTDL)
--   #{BATCH_TIME}       -> 실행 시각 (HH:MM)   (기본값: 00:20)
--   #{ADMIN_USER}       -> 등록/수정 사용자 ID  (기본값: admin)
-- ============================================================


-- 1. 기존 잡 정의 삭제
DELETE FROM #{DLM_SCHEMA}.TBL_PIIJOB       WHERE JOBID = '#{JOBID}';
DELETE FROM #{DLM_SCHEMA}.TBL_PIISTEP      WHERE JOBID = '#{JOBID}';
DELETE FROM #{DLM_SCHEMA}.TBL_PIISTEPTABLE WHERE JOBID = '#{JOBID}';


-- 2. JOB 등록
INSERT INTO #{DLM_SCHEMA}.TBL_PIIJOB (
    JOBID, VERSION, JOBNAME, `SYSTEM`, POLICY_ID, KEYMAP_ID,
    JOBTYPE, RUNTYPE, CALENDAR, `TIME`, CRONVAL, CONFIRMFLAG, STATUS, PHASE,
    JOB_OWNER_ID1, JOB_OWNER_NAME1,
    JOB_OWNER_ID2, JOB_OWNER_NAME2,
    JOB_OWNER_ID3, JOB_OWNER_NAME3,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', '#{JOBID}', NULL, NULL, NULL,
    'BATCH', 'DLM_BATCH', 'ALLDAYS', '#{BATCH_TIME}', '##########', 'N', 'ACTIVE', 'CHECKIN',
    '#{ADMIN_USER}', '#{ADMIN_USER}',
    NULL, NULL,
    NULL, NULL,
    NULL, NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);


-- 3. STEP 등록
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEP (
    JOBID, VERSION, STEPID, STEPNAME, STEPTYPE, STEPSEQ, DB,
    STATUS, PHASE, THREADCNT, COMMITCNT,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID,
    DATA_HANDLING_METHOD, PROCESSING_METHOD, FK_DISABLE_FLAG, INDEX_UNUSUAL_FLAG,
    VAL1, VAL2, VAL3, VAL4, VAL5
) VALUES (
    '#{JOBID}', '1', 'EXE_META_UPDATE', 'META_UPDATE', 'EXE_FINISH', 1, '#{DLM_DB}',
    'ACTIVE', 'CHECKOUT', 1, 5000,
    NULL, NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}',
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL
);


-- 4. STEPTABLE 등록 (4단계 순차 실행)

-- 4-1. TBL_METATABLE_OLD 백업 삭제
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_META_UPDATE', '#{DLM_DB}', '#{DLM_SCHEMA}', 'TBL_METATABLE_OLD',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    1, 10, 10, NULL,
    '', '', '', NULL, NULL,
    NULL, 'DELETE FROM #{DLM_SCHEMA}.TBL_METATABLE_OLD',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-2. TBL_METATABLE -> TBL_METATABLE_OLD 백업
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_META_UPDATE', '#{DLM_DB}', '#{DLM_SCHEMA}', 'TBL_METATABLE_OLD',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    1, 20, 10, NULL,
    '', '', '', NULL, NULL,
    NULL, 'INSERT INTO #{DLM_SCHEMA}.TBL_METATABLE_OLD SELECT * FROM #{DLM_SCHEMA}.TBL_METATABLE',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-3. TBL_METATABLE 전체 삭제
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_META_UPDATE', '#{DLM_DB}', '#{DLM_SCHEMA}', 'TBL_METATABLE',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    1, 30, 10, NULL,
    '', '', '', NULL, NULL,
    NULL, 'DELETE FROM #{DLM_SCHEMA}.TBL_METATABLE',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-4. TBL_PIITABLE + OLD + METASYSTEMDATA JOIN -> TBL_METATABLE 재적재
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_META_UPDATE', '#{DLM_DB}', '#{DLM_SCHEMA}', 'TBL_METATABLE',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    1, 40, 10, NULL,
    '', '', '', NULL, NULL,
    NULL,
'INSERT INTO #{DLM_SCHEMA}.TBL_METATABLE
SELECT
    p.DB,
    p.OWNER,
    p.TABLE_NAME,
    p.COLUMN_NAME,
    p.COLUMN_ID,
    p.PK_YN,
    p.PK_POSITION,
    p.FULL_DATA_TYPE,
    p.DATA_TYPE,
    p.DATA_LENGTH,
    s.DOMAIN,
    m.PIITYPE,
    m.PIIGRADE,
    m.ENCRIPT_FLAG,
    m.SCRAMBLE_TYPE,
    p.REGDATE,
    p.UPDDATE,
    m.REGUSERID,
    m.UPDUSERID,
    m.MASTERKEY,
    m.MASTERYN,
    s.tab_name_kr AS TABLE_COMMENT,
    COALESCE(p.COMMENTS, s.col_name_kr) AS COLUMN_COMMENT,
    m.VAL1,
    m.VAL2,
    m.VAL3,
    m.VAL4
FROM #{DLM_SCHEMA}.TBL_PIITABLE p
LEFT OUTER JOIN #{DLM_SCHEMA}.TBL_METATABLE_OLD m
    ON  p.DB          = m.DB
    AND p.OWNER       = m.OWNER
    AND p.TABLE_NAME  = m.TABLE_NAME
    AND p.COLUMN_NAME = m.COLUMN_NAME
LEFT OUTER JOIN #{DLM_SCHEMA}.TBL_METASYSTEMDATA s
    ON  p.DB          = s.DB
    AND p.OWNER       = s.OWNER
    AND p.TABLE_NAME  = s.TAB_NAME
    AND p.COLUMN_NAME = s.COL_NAME
WHERE p.OWNER != ''#{EXCLUDE_OWNER}''
  AND p.DB IN (#{TARGET_DB_LIST})',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);


COMMIT;
