-- ============================================================
-- DLM_BATCH_CATALOG (MariaDB) : 원천DB 카탈로그 수집 배치 잡
-- ============================================================
-- 원천 MariaDB의 INFORMATION_SCHEMA.COLUMNS에서 컬럼 메타데이터를
-- 수집하여 TBL_PIITABLE에 반영하는 배치 잡 등록 스크립트.
--
-- [배치 흐름]
--   Step1 EXTRACT_CATALOG : 원천DB에서 카탈로그 추출 -> TMP/NEW/OLD 비교 -> 반영
--   Step2 EXE_HOMECAST    : NEW/OLD 임시 테이블을 Home DB(DLM)로 전송
--   Step3 EXE_FINISH      : Home DB에 최종 반영 + 임시 테이블 정리
--
-- ============================================================
-- 사이트별 배포 시 아래 변수를 해당 사이트 값으로 치환(Replace All)하세요.
--
--   #{JOBID}               -> 잡 ID                 (예: DLM_BATCH_CATALOG_MARIADB_DLMARC)
--   #{SOURCE_DB}           -> 원천 DB명 (TBL_PIIDATABASE 등록명)  (예: DLMARC)
--   #{HOME_DB}             -> DLM Home DB명          (예: DLM)
--   #{DLM_SCHEMA}          -> DLM 스키마명           (예: COTDL)
--   #{TARGET_SCHEMA_LIST}  -> 수집 대상 스키마 목록  (예: ''PIIODS'',''PIICOOWNSER'',''PIICOOWNORG'')
--   #{BATCH_TIME}          -> 실행 시각 (HH:MM)      (예: 00:10)
--   #{ADMIN_USER}          -> 등록/수정 사용자 ID     (예: admin)
--
-- [참고] SQLSTR 내의 ''#DBNAME''은 DLM 엔진이 런타임에 치환하는 변수입니다.
--        이것은 수정하지 마세요.
-- ============================================================


-- 1. 기존 잡 정의 삭제
DELETE FROM #{DLM_SCHEMA}.TBL_PIIJOB       WHERE JOBID = '#{JOBID}';
DELETE FROM #{DLM_SCHEMA}.TBL_PIISTEP      WHERE JOBID = '#{JOBID}';
DELETE FROM #{DLM_SCHEMA}.TBL_PIISTEPTABLE WHERE JOBID = '#{JOBID}';


-- ============================================================
-- 2. JOB 등록
-- ============================================================
INSERT INTO #{DLM_SCHEMA}.TBL_PIIJOB (
    JOBID, VERSION, JOBNAME, `SYSTEM`, POLICY_ID, KEYMAP_ID,
    JOBTYPE, RUNTYPE, CALENDAR, `TIME`, CRONVAL, CONFIRMFLAG, STATUS, PHASE,
    JOB_OWNER_ID1, JOB_OWNER_NAME1,
    JOB_OWNER_ID2, JOB_OWNER_NAME2,
    JOB_OWNER_ID3, JOB_OWNER_NAME3,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', '#{JOBID}', NULL, NULL, NULL,
    'BATCH', 'DLM_BATCH', 'ALLDAYS', '#{BATCH_TIME}', '##########', 'N', 'ACTIVE', 'CHECKIN',
    '#{ADMIN_USER}', '#{ADMIN_USER}',
    NULL, NULL,
    NULL, NULL,
    NULL, NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);


-- ============================================================
-- 3. STEP 등록 (3단계)
-- ============================================================

-- Step1: 원천DB에서 카탈로그 추출
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEP (
    JOBID, VERSION, STEPID, STEPNAME, STEPTYPE, STEPSEQ, DB,
    STATUS, PHASE, THREADCNT, COMMITCNT,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXTRACT_CATALOG', 'CATALOG_EXTRACT', 'EXE_EXTRACT', 1, '#{SOURCE_DB}',
    'ACTIVE', 'CHECKOUT', 1, 5000,
    NULL, NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- Step2: 임시 테이블을 Home DB로 전송
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEP (
    JOBID, VERSION, STEPID, STEPNAME, STEPTYPE, STEPSEQ, DB,
    STATUS, PHASE, THREADCNT, COMMITCNT,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_HOMECAST', 'CATALOG_HOMECAST', 'EXE_HOMECAST', 2, '#{SOURCE_DB}',
    'ACTIVE', 'CHECKOUT', 10, 5000,
    NULL, NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- Step3: Home DB 최종 반영 + 정리
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEP (
    JOBID, VERSION, STEPID, STEPNAME, STEPTYPE, STEPSEQ, DB,
    STATUS, PHASE, THREADCNT, COMMITCNT,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_FINISH', 'CATALOG_FINISH', 'EXE_FINISH', 3, '#{SOURCE_DB}',
    'ACTIVE', 'CHECKOUT', 1, 5000,
    NULL, NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);


-- ============================================================
-- 4. STEPTABLE 등록
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- Step1: EXTRACT_CATALOG (원천DB에서 실행)
-- ────────────────────────────────────────────────────────────

-- 4-1-1. [SEQ 100] INFORMATION_SCHEMA -> TBL_PIITABLE_TMP (전체 카탈로그 추출)
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXTRACT_CATALOG', '#{SOURCE_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE_TMP',
    NULL, 'ADD', 'EXTRACT', NULL, NULL, NULL, NULL,
    10, 100, 10, NULL,
    '', NULL, NULL, NULL, NULL,
    NULL,
'INSERT INTO #{DLM_SCHEMA}.TBL_PIITABLE_TMP
SELECT ''#DBNAME''
    , UPPER(A.TABLE_SCHEMA) AS OWNER
    , UPPER(A.TABLE_NAME)
    , UPPER(A.COLUMN_NAME)
    , A.ORDINAL_POSITION AS COL_ORDER
    , CASE WHEN A.COLUMN_KEY = ''PRI'' THEN ''Y'' ELSE '''' END AS PK_YN
    , NULL AS PK_POSITION
    , UPPER(A.COLUMN_TYPE) AS FULL_DATA_TYPE
    , UPPER(A.DATA_TYPE)
    , A.CHARACTER_MAXIMUM_LENGTH
    , CASE WHEN A.IS_NULLABLE = ''YES'' THEN ''Y'' ELSE ''N'' END AS NULLABLE
    , SUBSTRING(A.COLUMN_COMMENT, 1, 200) AS COMMENTS
    , NOW()
    , NOW()
    , ''#{ADMIN_USER}''
    , ''#{ADMIN_USER}''
FROM INFORMATION_SCHEMA.COLUMNS A
WHERE A.TABLE_SCHEMA IN (#{TARGET_SCHEMA_LIST})
ORDER BY 1, 2, 3, 5',
    NULL, NULL, NULL, NULL, NULL,
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-1-2. [SEQ 200] TBL_PIITABLE_NEW 추출 (신규/변경 컬럼 = TMP에 있고 기존에 없는 것)
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXTRACT_CATALOG', '#{SOURCE_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE_NEW',
    NULL, 'ADD', 'EXTRACT', NULL, NULL, NULL, NULL,
    10, 200, 10, NULL,
    '', NULL, NULL, NULL, NULL,
    NULL,
'INSERT INTO #{DLM_SCHEMA}.TBL_PIITABLE_NEW
SELECT * FROM #{DLM_SCHEMA}.TBL_PIITABLE_TMP
WHERE NOT EXISTS (
    SELECT 1
    FROM #{DLM_SCHEMA}.TBL_PIITABLE e
    WHERE e.DB             = #{DLM_SCHEMA}.TBL_PIITABLE_TMP.DB
      AND e.owner          = #{DLM_SCHEMA}.TBL_PIITABLE_TMP.owner
      AND e.table_name     = #{DLM_SCHEMA}.TBL_PIITABLE_TMP.table_name
      AND e.column_name    = #{DLM_SCHEMA}.TBL_PIITABLE_TMP.column_name
      AND e.column_id      = #{DLM_SCHEMA}.TBL_PIITABLE_TMP.column_id
      AND COALESCE(e.pk_yn, ''0'')          = COALESCE(#{DLM_SCHEMA}.TBL_PIITABLE_TMP.pk_yn, ''0'')
      AND e.full_data_type = #{DLM_SCHEMA}.TBL_PIITABLE_TMP.full_data_type
      AND e.data_type      = #{DLM_SCHEMA}.TBL_PIITABLE_TMP.data_type
      AND COALESCE(e.data_length, 0)        = COALESCE(#{DLM_SCHEMA}.TBL_PIITABLE_TMP.data_length, 0)
      AND COALESCE(e.nullable, ''0'')       = COALESCE(#{DLM_SCHEMA}.TBL_PIITABLE_TMP.nullable, ''0'')
)
AND #{DLM_SCHEMA}.TBL_PIITABLE_TMP.DB = ''#DBNAME''',
    NULL, NULL, NULL, NULL, NULL,
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-1-3. [SEQ 300] TBL_PIITABLE_OLD 추출 (삭제/변경 컬럼 = 기존에 있고 TMP에 없는 것)
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXTRACT_CATALOG', '#{SOURCE_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE_OLD',
    NULL, 'ADD', 'EXTRACT', NULL, NULL, NULL, NULL,
    10, 300, 10, NULL,
    '', NULL, NULL, NULL, NULL,
    NULL,
'INSERT INTO #{DLM_SCHEMA}.TBL_PIITABLE_OLD
SELECT * FROM #{DLM_SCHEMA}.TBL_PIITABLE
WHERE NOT EXISTS (
    SELECT 1
    FROM #{DLM_SCHEMA}.TBL_PIITABLE_TMP e
    WHERE e.DB             = #{DLM_SCHEMA}.TBL_PIITABLE.DB
      AND e.owner          = #{DLM_SCHEMA}.TBL_PIITABLE.owner
      AND e.table_name     = #{DLM_SCHEMA}.TBL_PIITABLE.table_name
      AND e.column_name    = #{DLM_SCHEMA}.TBL_PIITABLE.column_name
      AND e.column_id      = #{DLM_SCHEMA}.TBL_PIITABLE.column_id
      AND COALESCE(e.pk_yn, ''0'')          = COALESCE(#{DLM_SCHEMA}.TBL_PIITABLE.pk_yn, ''0'')
      AND e.full_data_type = #{DLM_SCHEMA}.TBL_PIITABLE.full_data_type
      AND e.data_type      = #{DLM_SCHEMA}.TBL_PIITABLE.data_type
      AND COALESCE(e.data_length, 0)        = COALESCE(#{DLM_SCHEMA}.TBL_PIITABLE.data_length, 0)
      AND COALESCE(e.nullable, ''0'')       = COALESCE(#{DLM_SCHEMA}.TBL_PIITABLE.nullable, ''0'')
)
AND #{DLM_SCHEMA}.TBL_PIITABLE.DB = ''#DBNAME''',
    NULL, NULL, NULL, NULL, NULL,
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-1-4. [SEQ 400] 변경/삭제 컬럼을 TBL_PIITABLE에서 제거
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXTRACT_CATALOG', '#{SOURCE_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE',
    NULL, 'ADD', 'EXTRACT', NULL, NULL, NULL, NULL,
    10, 400, 10, NULL,
    '', NULL, NULL, NULL, NULL,
    NULL,
'DELETE FROM #{DLM_SCHEMA}.TBL_PIITABLE
WHERE EXISTS (
    SELECT 1
    FROM #{DLM_SCHEMA}.TBL_PIITABLE_OLD e
    WHERE e.DB          = #{DLM_SCHEMA}.TBL_PIITABLE.DB
      AND e.owner       = #{DLM_SCHEMA}.TBL_PIITABLE.owner
      AND e.table_name  = #{DLM_SCHEMA}.TBL_PIITABLE.table_name
      AND e.column_name = #{DLM_SCHEMA}.TBL_PIITABLE.column_name
)
AND #{DLM_SCHEMA}.TBL_PIITABLE.DB = ''#DBNAME''',
    NULL, NULL, NULL, NULL, NULL,
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-1-5. [SEQ 500] 신규/변경 컬럼을 TBL_PIITABLE에 반영
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXTRACT_CATALOG', '#{SOURCE_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE',
    NULL, 'ADD', 'EXTRACT', NULL, NULL, NULL, NULL,
    10, 500, 10, NULL,
    '', NULL, NULL, NULL, NULL,
    NULL,
'INSERT INTO #{DLM_SCHEMA}.TBL_PIITABLE
SELECT *
FROM #{DLM_SCHEMA}.TBL_PIITABLE_NEW
WHERE DB = ''#DBNAME''',
    NULL, NULL, NULL, NULL, NULL,
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);


-- ────────────────────────────────────────────────────────────
-- Step2: EXE_HOMECAST (원천DB -> Home DB 전송)
-- ────────────────────────────────────────────────────────────

-- 4-2-1. [SEQ 100] TBL_PIITABLE_NEW를 Home DB로 전송
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_HOMECAST', '#{SOURCE_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE_NEW',
    NULL, NULL, 'HOMECAST', NULL, NULL, NULL, NULL,
    10, 100, 10, NULL,
    NULL, NULL, NULL, NULL, NULL,
    ' ',
'INSERT INTO #{DLM_SCHEMA}.TBL_PIITABLE_NEW
SELECT * FROM #{DLM_SCHEMA}.TBL_PIITABLE_NEW',
    NULL, NULL, NULL, NULL, 'AUTO',
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-2-2. [SEQ 200] TBL_PIITABLE_OLD를 Home DB로 전송
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_HOMECAST', '#{SOURCE_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE_OLD',
    NULL, NULL, 'HOMECAST', NULL, NULL, NULL, NULL,
    10, 200, 10, NULL,
    NULL, NULL, NULL, NULL, NULL,
    ' ',
'INSERT INTO #{DLM_SCHEMA}.TBL_PIITABLE_OLD
SELECT * FROM #{DLM_SCHEMA}.TBL_PIITABLE_OLD',
    NULL, NULL, NULL, NULL, 'AUTO',
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);


-- ────────────────────────────────────────────────────────────
-- Step3: EXE_FINISH (정리 + Home DB 최종 반영)
-- ────────────────────────────────────────────────────────────

-- 4-3-1. [SEQ 100] 원천DB TBL_PIITABLE_NEW 정리
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_FINISH', '#{SOURCE_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE_NEW',
    NULL, NULL, 'FINISH', NULL, NULL, NULL, NULL,
    10, 100, 10, NULL,
    NULL, NULL, NULL, NULL, NULL,
    ' ',
'DELETE FROM #{DLM_SCHEMA}.TBL_PIITABLE_NEW',
    NULL, NULL, NULL, NULL, 'AUTO',
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-3-2. [SEQ 200] 원천DB TBL_PIITABLE_OLD 정리
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_FINISH', '#{SOURCE_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE_OLD',
    NULL, NULL, 'FINISH', NULL, NULL, NULL, NULL,
    10, 200, 10, NULL,
    NULL, NULL, NULL, NULL, NULL,
    ' ',
'DELETE FROM #{DLM_SCHEMA}.TBL_PIITABLE_OLD',
    NULL, NULL, NULL, NULL, 'AUTO',
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-3-3. [SEQ 300] 원천DB TBL_PIITABLE_TMP 정리
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_FINISH', '#{SOURCE_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE_TMP',
    NULL, NULL, 'FINISH', NULL, NULL, NULL, NULL,
    10, 300, 10, NULL,
    NULL, NULL, NULL, NULL, NULL,
    ' ',
'DELETE FROM #{DLM_SCHEMA}.TBL_PIITABLE_TMP',
    NULL, NULL, NULL, NULL, 'AUTO',
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-3-4. [SEQ 400] Home DB: 변경/삭제 컬럼을 TBL_PIITABLE에서 제거
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_FINISH', '#{HOME_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE',
    NULL, NULL, 'FINISH', NULL, NULL, NULL, NULL,
    10, 400, 10, NULL,
    NULL, NULL, NULL, NULL, NULL,
    ' ',
'DELETE FROM #{DLM_SCHEMA}.TBL_PIITABLE
WHERE EXISTS (
    SELECT 1
    FROM #{DLM_SCHEMA}.TBL_PIITABLE_OLD e
    WHERE e.DB = ''#{SOURCE_DB}''
      AND e.DB          = #{DLM_SCHEMA}.TBL_PIITABLE.DB
      AND e.owner       = #{DLM_SCHEMA}.TBL_PIITABLE.owner
      AND e.table_name  = #{DLM_SCHEMA}.TBL_PIITABLE.table_name
      AND e.column_name = #{DLM_SCHEMA}.TBL_PIITABLE.column_name
)',
    NULL, NULL, NULL, NULL, 'AUTO',
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-3-5. [SEQ 500] Home DB: 신규/변경 컬럼을 TBL_PIITABLE에 반영
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_FINISH', '#{HOME_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE',
    NULL, NULL, 'FINISH', NULL, NULL, NULL, NULL,
    10, 500, 10, NULL,
    NULL, NULL, NULL, NULL, NULL,
    ' ',
'INSERT INTO #{DLM_SCHEMA}.TBL_PIITABLE
SELECT * FROM #{DLM_SCHEMA}.TBL_PIITABLE_NEW
WHERE DB = ''#{SOURCE_DB}''',
    NULL, NULL, NULL, NULL, 'AUTO',
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-3-6. [SEQ 600] Home DB: TBL_PIITABLE_NEW 정리
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_FINISH', '#{HOME_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE_NEW',
    NULL, NULL, 'FINISH', NULL, NULL, NULL, NULL,
    10, 600, 10, NULL,
    NULL, NULL, NULL, NULL, NULL,
    ' ',
'DELETE FROM #{DLM_SCHEMA}.TBL_PIITABLE_NEW
WHERE DB = ''#{SOURCE_DB}''',
    NULL, NULL, NULL, NULL, 'AUTO',
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);

-- 4-3-7. [SEQ 700] Home DB: TBL_PIITABLE_OLD 정리
INSERT INTO #{DLM_SCHEMA}.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    '#{JOBID}', '1', 'EXE_FINISH', '#{HOME_DB}', '#{DLM_SCHEMA}', 'TBL_PIITABLE_OLD',
    NULL, NULL, 'FINISH', NULL, NULL, NULL, NULL,
    10, 700, 10, NULL,
    NULL, NULL, NULL, NULL, NULL,
    ' ',
'DELETE FROM #{DLM_SCHEMA}.TBL_PIITABLE_OLD
WHERE DB = ''#{SOURCE_DB}''',
    NULL, NULL, NULL, NULL, 'AUTO',
    NOW(), NOW(), '#{ADMIN_USER}', '#{ADMIN_USER}'
);


COMMIT;
