-- ============================================================
-- DLM_BATCH_METADATA_UPDATE : TBL_METATABLE 일일 갱신 배치 잡
-- ============================================================
-- 이 파일은 기본값으로 변수가 치환된 WORKING 파일입니다.
-- 원본: DLM_JOB_BATCH_METADATA.sql
--
-- 적용된 변수값:
--   JOBID            = DLM_BATCH_METADATA_UPDATE
--   DLM_DB           = DLM
--   DLM_SCHEMA       = COTDL
--   TARGET_DB_LIST   = ''DAON'',''DW''
--   EXCLUDE_OWNER    = COTDL
--   BATCH_TIME       = 00:20
--   ADMIN_USER       = admin
-- ============================================================


-- 1. 기존 잡 정의 삭제
DELETE FROM COTDL.TBL_PIIJOB       WHERE JOBID = 'DLM_BATCH_METADATA_UPDATE';
DELETE FROM COTDL.TBL_PIISTEP      WHERE JOBID = 'DLM_BATCH_METADATA_UPDATE';
DELETE FROM COTDL.TBL_PIISTEPTABLE WHERE JOBID = 'DLM_BATCH_METADATA_UPDATE';


-- 2. JOB 등록
INSERT INTO COTDL.TBL_PIIJOB (
    JOBID, VERSION, JOBNAME, `SYSTEM`, POLICY_ID, KEYMAP_ID,
    JOBTYPE, RUNTYPE, CALENDAR, `TIME`, CRONVAL, CONFIRMFLAG, STATUS, PHASE,
    JOB_OWNER_ID1, JOB_OWNER_NAME1,
    JOB_OWNER_ID2, JOB_OWNER_NAME2,
    JOB_OWNER_ID3, JOB_OWNER_NAME3,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_METADATA_UPDATE', '1', 'DLM_BATCH_METADATA_UPDATE', NULL, NULL, NULL,
    'BATCH', 'DLM_BATCH', 'ALLDAYS', '00:20', '##########', 'N', 'ACTIVE', 'CHECKIN',
    'admin', 'admin',
    NULL, NULL,
    NULL, NULL,
    NULL, NOW(), NOW(), 'admin', 'admin'
);


-- 3. STEP 등록
INSERT INTO COTDL.TBL_PIISTEP (
    JOBID, VERSION, STEPID, STEPNAME, STEPTYPE, STEPSEQ, DB,
    STATUS, PHASE, THREADCNT, COMMITCNT,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID,
    DATA_HANDLING_METHOD, PROCESSING_METHOD, FK_DISABLE_FLAG, INDEX_UNUSUAL_FLAG,
    VAL1, VAL2, VAL3, VAL4, VAL5
) VALUES (
    'DLM_BATCH_METADATA_UPDATE', '1', 'EXE_META_UPDATE', 'META_UPDATE', 'EXE_FINISH', 1, 'DLM',
    'ACTIVE', 'CHECKOUT', 1, 5000,
    NULL, NOW(), NOW(), 'admin', 'admin',
    NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL
);


-- 4. STEPTABLE 등록 (4단계 순차 실행)

-- 4-1. TBL_METATABLE_OLD 백업 삭제
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_METADATA_UPDATE', '1', 'EXE_META_UPDATE', 'DLM', 'COTDL', 'TBL_METATABLE_OLD',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    1, 10, 10, NULL,
    '', '', '', NULL, NULL,
    NULL, 'DELETE FROM COTDL.TBL_METATABLE_OLD',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-2. TBL_METATABLE -> TBL_METATABLE_OLD 백업
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_METADATA_UPDATE', '1', 'EXE_META_UPDATE', 'DLM', 'COTDL', 'TBL_METATABLE_OLD',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    1, 20, 10, NULL,
    '', '', '', NULL, NULL,
    NULL, 'INSERT INTO COTDL.TBL_METATABLE_OLD SELECT * FROM COTDL.TBL_METATABLE',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-3. TBL_METATABLE 전체 삭제
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_METADATA_UPDATE', '1', 'EXE_META_UPDATE', 'DLM', 'COTDL', 'TBL_METATABLE',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    1, 30, 10, NULL,
    '', '', '', NULL, NULL,
    NULL, 'DELETE FROM COTDL.TBL_METATABLE',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-4. TBL_PIITABLE + OLD + METASYSTEMDATA JOIN -> TBL_METATABLE 재적재
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_METADATA_UPDATE', '1', 'EXE_META_UPDATE', 'DLM', 'COTDL', 'TBL_METATABLE',
    NULL, NULL, 'FINISH', '', '', NULL, NULL,
    1, 40, 10, NULL,
    '', '', '', NULL, NULL,
    NULL,
'INSERT INTO COTDL.TBL_METATABLE
SELECT
    p.DB,
    p.OWNER,
    p.TABLE_NAME,
    p.COLUMN_NAME,
    p.COLUMN_ID,
    p.PK_YN,
    p.PK_POSITION,
    p.FULL_DATA_TYPE,
    p.DATA_TYPE,
    p.DATA_LENGTH,
    s.DOMAIN,
    m.PIITYPE,
    m.PIIGRADE,
    m.ENCRIPT_FLAG,
    m.SCRAMBLE_TYPE,
    p.REGDATE,
    p.UPDDATE,
    m.REGUSERID,
    m.UPDUSERID,
    m.MASTERKEY,
    m.MASTERYN,
    s.tab_name_kr AS TABLE_COMMENT,
    COALESCE(p.COMMENTS, s.col_name_kr) AS COLUMN_COMMENT,
    m.VAL1,
    m.VAL2,
    m.VAL3,
    m.VAL4
FROM COTDL.TBL_PIITABLE p
LEFT OUTER JOIN COTDL.TBL_METATABLE_OLD m
    ON  p.DB          = m.DB
    AND p.OWNER       = m.OWNER
    AND p.TABLE_NAME  = m.TABLE_NAME
    AND p.COLUMN_NAME = m.COLUMN_NAME
LEFT OUTER JOIN COTDL.TBL_METASYSTEMDATA s
    ON  p.DB          = s.DB
    AND p.OWNER       = s.OWNER
    AND p.TABLE_NAME  = s.TAB_NAME
    AND p.COLUMN_NAME = s.COL_NAME
WHERE p.OWNER != ''COTDL''
  AND p.DB IN (''DAON'',''DW'')',
    NULL, NULL, NULL, '', NULL,
    NOW(), NOW(), 'admin', 'admin'
);


COMMIT;
