-- ============================================================
-- DLM_BATCH_CATALOG_MARIADB_DLM : DLM 자체 카탈로그 수집 배치 잡
-- ============================================================
-- DLM Home DB 자체의 INFORMATION_SCHEMA.COLUMNS에서 컬럼 메타데이터를
-- 수집하여 TBL_PIITABLE에 반영하는 배치 잡 등록 스크립트.
--
-- [특징] 원천DB = Home DB(DLM) 이므로 HOMECAST/FINISH 불필요.
--        단일 Step에서 추출 → 비교 → 반영 → 정리까지 완료.
--
-- [배치 흐름]
--   Step1 EXTRACT_CATALOG : 카탈로그 추출 -> TMP/NEW/OLD 비교 -> 반영 -> 정리
--
-- ============================================================
-- 사이트별 배포 시 아래 변수를 해당 사이트 값으로 치환(Replace All)하세요.
--
--   DLM_BATCH_CATALOG_MARIADB_DLM  -> 잡 ID
--   DLM            -> DB명 (TBL_PIIDATABASE 등록명)
--   COTDL          -> DLM 스키마명
--   ''COTDL''      -> 수집 대상 스키마 목록
--   NULL           -> 실행 시각 (HH:MM)
--   admin          -> 등록/수정 사용자 ID
--
-- [참고] SQLSTR 내의 ''#DBNAME''은 DLM 엔진이 런타임에 치환하는 변수입니다.
-- ============================================================


-- 1. 기존 잡 정의 삭제
DELETE FROM COTDL.TBL_PIIJOB       WHERE JOBID = 'DLM_BATCH_CATALOG_MARIADB_DLM';
DELETE FROM COTDL.TBL_PIISTEP      WHERE JOBID = 'DLM_BATCH_CATALOG_MARIADB_DLM';
DELETE FROM COTDL.TBL_PIISTEPTABLE WHERE JOBID = 'DLM_BATCH_CATALOG_MARIADB_DLM';


-- ============================================================
-- 2. JOB 등록
-- ============================================================
INSERT INTO COTDL.TBL_PIIJOB (
    JOBID, VERSION, JOBNAME, `SYSTEM`, POLICY_ID, KEYMAP_ID,
    JOBTYPE, RUNTYPE, CALENDAR, `TIME`, CRONVAL, CONFIRMFLAG, STATUS, PHASE,
    JOB_OWNER_ID1, JOB_OWNER_NAME1,
    JOB_OWNER_ID2, JOB_OWNER_NAME2,
    JOB_OWNER_ID3, JOB_OWNER_NAME3,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_CATALOG_MARIADB_DLM', '1', 'DLM_BATCH_CATALOG_MARIADB_DLM', NULL, NULL, NULL,
    'BATCH', 'IRREGULAR', 'ALLDAYS', 'NULL', '##########', 'N', 'ACTIVE', 'CHECKIN',
    'admin', 'admin',
    NULL, NULL,
    NULL, NULL,
    NULL, NOW(), NOW(), 'admin', 'admin'
);


-- ============================================================
-- 3. STEP 등록 (단일 Step — HOMECAST/FINISH 불필요)
-- ============================================================

INSERT INTO COTDL.TBL_PIISTEP (
    JOBID, VERSION, STEPID, STEPNAME, STEPTYPE, STEPSEQ, DB,
    STATUS, PHASE, THREADCNT, COMMITCNT,
    ENDDATE, REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_CATALOG_MARIADB_DLM', '1', 'EXTRACT_CATALOG', 'CATALOG_EXTRACT', 'EXE_EXTRACT', 1, 'DLM',
    'ACTIVE', 'CHECKOUT', 1, 5000,
    NULL, NOW(), NOW(), 'admin', 'admin'
);


-- ============================================================
-- 4. STEPTABLE 등록 (추출 → 비교 → 반영 → 정리)
-- ============================================================

-- 4-1. [SEQ 100] INFORMATION_SCHEMA -> TBL_PIITABLE_TMP (전체 카탈로그 추출)
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_CATALOG_MARIADB_DLM', '1', 'EXTRACT_CATALOG', 'DLM', 'COTDL', 'TBL_PIITABLE_TMP',
    NULL, 'ADD', 'EXTRACT', NULL, NULL, NULL, NULL,
    10, 100, 10, NULL,
    '대상 카탈로그 전체 정보 추출', NULL, NULL, NULL, NULL,
    NULL,
'INSERT INTO COTDL.TBL_PIITABLE_TMP
SELECT ''#DBNAME''
    , UPPER(A.TABLE_SCHEMA) AS OWNER
    , UPPER(A.TABLE_NAME)
    , UPPER(A.COLUMN_NAME)
    , A.ORDINAL_POSITION AS COL_ORDER
    , CASE WHEN A.COLUMN_KEY = ''PRI'' THEN ''Y'' ELSE '''' END AS PK_YN
    , NULL AS PK_POSITION
    , UPPER(A.COLUMN_TYPE) AS FULL_DATA_TYPE
    , UPPER(A.DATA_TYPE)
    , A.CHARACTER_MAXIMUM_LENGTH
    , CASE WHEN A.IS_NULLABLE = ''YES'' THEN ''Y'' ELSE ''N'' END AS NULLABLE
    , SUBSTRING(A.COLUMN_COMMENT, 1, 200) AS COMMENTS
    , NOW()
    , NOW()
    , ''admin''
    , ''admin''
FROM INFORMATION_SCHEMA.COLUMNS A
WHERE A.TABLE_SCHEMA IN (''COTDL'')
ORDER BY 1, 2, 3, 5',
    NULL, NULL, NULL, NULL, NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-2. [SEQ 200] TBL_PIITABLE_NEW 추출 (신규/변경 컬럼)
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_CATALOG_MARIADB_DLM', '1', 'EXTRACT_CATALOG', 'DLM', 'COTDL', 'TBL_PIITABLE_NEW',
    NULL, 'ADD', 'EXTRACT', NULL, NULL, NULL, NULL,
    10, 200, 10, NULL,
    '카탈로그 신규 변동 대상 추출', NULL, NULL, NULL, NULL,
    NULL,
'INSERT INTO COTDL.TBL_PIITABLE_NEW
SELECT * FROM COTDL.TBL_PIITABLE_TMP
WHERE NOT EXISTS (
    SELECT 1
    FROM COTDL.TBL_PIITABLE e
    WHERE e.DB             = COTDL.TBL_PIITABLE_TMP.DB
      AND e.owner          = COTDL.TBL_PIITABLE_TMP.owner
      AND e.table_name     = COTDL.TBL_PIITABLE_TMP.table_name
      AND e.column_name    = COTDL.TBL_PIITABLE_TMP.column_name
      AND e.column_id      = COTDL.TBL_PIITABLE_TMP.column_id
      AND COALESCE(e.pk_yn, ''0'')          = COALESCE(COTDL.TBL_PIITABLE_TMP.pk_yn, ''0'')
      AND e.full_data_type = COTDL.TBL_PIITABLE_TMP.full_data_type
      AND e.data_type      = COTDL.TBL_PIITABLE_TMP.data_type
      AND COALESCE(e.data_length, 0)        = COALESCE(COTDL.TBL_PIITABLE_TMP.data_length, 0)
      AND COALESCE(e.nullable, ''0'')       = COALESCE(COTDL.TBL_PIITABLE_TMP.nullable, ''0'')
)
AND COTDL.TBL_PIITABLE_TMP.DB = ''#DBNAME''',
    NULL, NULL, NULL, NULL, NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-3. [SEQ 300] TBL_PIITABLE_OLD 추출 (삭제/변경 컬럼)
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_CATALOG_MARIADB_DLM', '1', 'EXTRACT_CATALOG', 'DLM', 'COTDL', 'TBL_PIITABLE_OLD',
    NULL, 'ADD', 'EXTRACT', NULL, NULL, NULL, NULL,
    10, 300, 10, NULL,
    '기존 추출 대상 정보 추출', NULL, NULL, NULL, NULL,
    NULL,
'INSERT INTO COTDL.TBL_PIITABLE_OLD
SELECT * FROM COTDL.TBL_PIITABLE
WHERE NOT EXISTS (
    SELECT 1
    FROM COTDL.TBL_PIITABLE_TMP e
    WHERE e.DB             = COTDL.TBL_PIITABLE.DB
      AND e.owner          = COTDL.TBL_PIITABLE.owner
      AND e.table_name     = COTDL.TBL_PIITABLE.table_name
      AND e.column_name    = COTDL.TBL_PIITABLE.column_name
      AND e.column_id      = COTDL.TBL_PIITABLE.column_id
      AND COALESCE(e.pk_yn, ''0'')          = COALESCE(COTDL.TBL_PIITABLE.pk_yn, ''0'')
      AND e.full_data_type = COTDL.TBL_PIITABLE.full_data_type
      AND e.data_type      = COTDL.TBL_PIITABLE.data_type
      AND COALESCE(e.data_length, 0)        = COALESCE(COTDL.TBL_PIITABLE.data_length, 0)
      AND COALESCE(e.nullable, ''0'')       = COALESCE(COTDL.TBL_PIITABLE.nullable, ''0'')
)
AND COTDL.TBL_PIITABLE.DB = ''#DBNAME''',
    NULL, NULL, NULL, NULL, NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-4. [SEQ 400] 변경/삭제 컬럼을 TBL_PIITABLE에서 제거
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_CATALOG_MARIADB_DLM', '1', 'EXTRACT_CATALOG', 'DLM', 'COTDL', 'TBL_PIITABLE',
    NULL, 'EXCLUDE', 'EXTRACT', NULL, NULL, NULL, NULL,
    10, 400, 10, NULL,
    '기존 추출 카탈로그 정보 제거', NULL, NULL, NULL, NULL,
    NULL,
'DELETE FROM COTDL.TBL_PIITABLE
WHERE EXISTS (
    SELECT 1
    FROM COTDL.TBL_PIITABLE_OLD e
    WHERE e.DB          = COTDL.TBL_PIITABLE.DB
      AND e.owner       = COTDL.TBL_PIITABLE.owner
      AND e.table_name  = COTDL.TBL_PIITABLE.table_name
      AND e.column_name = COTDL.TBL_PIITABLE.column_name
)
AND COTDL.TBL_PIITABLE.DB = ''#DBNAME''',
    NULL, NULL, NULL, NULL, NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-5. [SEQ 500] 신규/변경 컬럼을 TBL_PIITABLE에 반영
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_CATALOG_MARIADB_DLM', '1', 'EXTRACT_CATALOG', 'DLM', 'COTDL', 'TBL_PIITABLE',
    NULL, 'ADD', 'EXTRACT', NULL, NULL, NULL, NULL,
    10, 500, 10, NULL,
    '최종 카탈로그 반영분 집계', NULL, NULL, NULL, NULL,
    NULL,
'INSERT INTO COTDL.TBL_PIITABLE
SELECT *
FROM COTDL.TBL_PIITABLE_NEW
WHERE DB = ''#DBNAME''',
    NULL, NULL, NULL, NULL, NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-6. [SEQ 600] TBL_PIITABLE_TMP 정리
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_CATALOG_MARIADB_DLM', '1', 'EXTRACT_CATALOG', 'DLM', 'COTDL', 'TBL_PIITABLE_TMP',
    NULL, 'ETC', 'EXTRACT', NULL, NULL, NULL, NULL,
    10, 600, 10, NULL,
    '임시 테이블 TMP 정리', NULL, NULL, NULL, NULL,
    NULL,
'DELETE FROM COTDL.TBL_PIITABLE_TMP
WHERE DB = ''#DBNAME''',
    NULL, NULL, NULL, NULL, NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-7. [SEQ 700] TBL_PIITABLE_NEW 정리
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_CATALOG_MARIADB_DLM', '1', 'EXTRACT_CATALOG', 'DLM', 'COTDL', 'TBL_PIITABLE_NEW',
    NULL, 'ETC', 'EXTRACT', NULL, NULL, NULL, NULL,
    10, 700, 10, NULL,
    '임시 테이블 NEW 정리', NULL, NULL, NULL, NULL,
    NULL,
'DELETE FROM COTDL.TBL_PIITABLE_NEW
WHERE DB = ''#DBNAME''',
    NULL, NULL, NULL, NULL, NULL,
    NOW(), NOW(), 'admin', 'admin'
);

-- 4-8. [SEQ 800] TBL_PIITABLE_OLD 정리
INSERT INTO COTDL.TBL_PIISTEPTABLE (
    JOBID, VERSION, STEPID, DB, OWNER, TABLE_NAME,
    PAGITYPE, PAGITYPEDETAIL, EXETYPE, ARCHIVEFLAG, STATUS, `PRECEDING`, SUCCEDDING,
    SEQ1, SEQ2, SEQ3, PIPELINE,
    PK_COL, WHERE_COL, WHERE_KEY_NAME, PARALLELCNT, COMMITCNT,
    WHERESTR, SQLSTR,
    KEYMAP_ID, KEY_NAME, KEY_COLS, KEY_REFSTR, SQLTYPE,
    REGDATE, UPDDATE, REGUSERID, UPDUSERID
) VALUES (
    'DLM_BATCH_CATALOG_MARIADB_DLM', '1', 'EXTRACT_CATALOG', 'DLM', 'COTDL', 'TBL_PIITABLE_OLD',
    NULL, 'ETC', 'EXTRACT', NULL, NULL, NULL, NULL,
    10, 800, 10, NULL,
    '임시 테이블 OLD 정리', NULL, NULL, NULL, NULL,
    NULL,
'DELETE FROM COTDL.TBL_PIITABLE_OLD
WHERE DB = ''#DBNAME''',
    NULL, NULL, NULL, NULL, NULL,
    NOW(), NOW(), 'admin', 'admin'
);


COMMIT;
