-- ============================================================
-- PATCH: TBL_MEMBER 계열 소명 워크플로우 지원 컬럼 추가
-- Date: 2026-04-11
-- Description: 이상행위 소명 자동화를 위한 이메일, 상위결재자, 직위 컬럼 추가
-- 대상: TBL_MEMBER, TBL_MEMBER_TMP, TBL_MEMBER_NEW, TBL_MEMBER_OLD
-- ============================================================


-- ************************************************************
-- [MariaDB / MySQL]
-- ************************************************************

-- ========== TBL_MEMBER ==========
ALTER TABLE COTDL.TBL_MEMBER ADD COLUMN IF NOT EXISTS EMAIL VARCHAR(200) NULL COMMENT '이메일';
ALTER TABLE COTDL.TBL_MEMBER ADD COLUMN IF NOT EXISTS MANAGER_ID VARCHAR(50) NULL COMMENT '상위결재자 ID (FK: COTDL.TBL_MEMBER.USERID)';
ALTER TABLE COTDL.TBL_MEMBER ADD COLUMN IF NOT EXISTS POSITION VARCHAR(50) NULL COMMENT '직위/직급';

-- ========== TBL_MEMBER_TMP ==========
ALTER TABLE COTDL.TBL_MEMBER_TMP ADD COLUMN IF NOT EXISTS TELNO VARCHAR(20) NULL COMMENT '전화번호';
ALTER TABLE COTDL.TBL_MEMBER_TMP ADD COLUMN IF NOT EXISTS GRADE VARCHAR(20) NULL COMMENT '등급';
ALTER TABLE COTDL.TBL_MEMBER_TMP ADD COLUMN IF NOT EXISTS EMAIL VARCHAR(200) NULL COMMENT '이메일';
ALTER TABLE COTDL.TBL_MEMBER_TMP ADD COLUMN IF NOT EXISTS MANAGER_ID VARCHAR(50) NULL COMMENT '상위결재자 ID';
ALTER TABLE COTDL.TBL_MEMBER_TMP ADD COLUMN IF NOT EXISTS POSITION VARCHAR(50) NULL COMMENT '직위/직급';

-- ========== TBL_MEMBER_NEW ==========
ALTER TABLE COTDL.TBL_MEMBER_NEW ADD COLUMN IF NOT EXISTS TELNO VARCHAR(20) NULL COMMENT '전화번호';
ALTER TABLE COTDL.TBL_MEMBER_NEW ADD COLUMN IF NOT EXISTS GRADE VARCHAR(20) NULL COMMENT '등급';
ALTER TABLE COTDL.TBL_MEMBER_NEW ADD COLUMN IF NOT EXISTS EMAIL VARCHAR(200) NULL COMMENT '이메일';
ALTER TABLE COTDL.TBL_MEMBER_NEW ADD COLUMN IF NOT EXISTS MANAGER_ID VARCHAR(50) NULL COMMENT '상위결재자 ID';
ALTER TABLE COTDL.TBL_MEMBER_NEW ADD COLUMN IF NOT EXISTS POSITION VARCHAR(50) NULL COMMENT '직위/직급';

-- ========== TBL_MEMBER_OLD ==========
ALTER TABLE COTDL.TBL_MEMBER_OLD ADD COLUMN IF NOT EXISTS TELNO VARCHAR(20) NULL COMMENT '전화번호';
ALTER TABLE COTDL.TBL_MEMBER_OLD ADD COLUMN IF NOT EXISTS GRADE VARCHAR(20) NULL COMMENT '등급';
ALTER TABLE COTDL.TBL_MEMBER_OLD ADD COLUMN IF NOT EXISTS EMAIL VARCHAR(200) NULL COMMENT '이메일';
ALTER TABLE COTDL.TBL_MEMBER_OLD ADD COLUMN IF NOT EXISTS MANAGER_ID VARCHAR(50) NULL COMMENT '상위결재자 ID';
ALTER TABLE COTDL.TBL_MEMBER_OLD ADD COLUMN IF NOT EXISTS POSITION VARCHAR(50) NULL COMMENT '직위/직급';


-- ************************************************************
-- [Oracle] — 원천DB에도 동일 테이블이 있는 경우 수행
-- Oracle은 IF NOT EXISTS 미지원이므로 컬럼 존재 시 에러 무시 처리
-- SQL*Plus: 각 ALTER 수행 후 에러 무시하려면 아래 주석 해제
-- WHENEVER SQLERROR CONTINUE
-- ************************************************************

-- -- ========== TBL_MEMBER ==========
-- ALTER TABLE COTDL.TBL_MEMBER ADD (EMAIL VARCHAR2(200));
-- ALTER TABLE COTDL.TBL_MEMBER ADD (MANAGER_ID VARCHAR2(50));
-- ALTER TABLE COTDL.TBL_MEMBER ADD (POSITION VARCHAR2(50));
-- COMMENT ON COLUMN COTDL.TBL_MEMBER.EMAIL IS '이메일';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER.MANAGER_ID IS '상위결재자 ID';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER.POSITION IS '직위/직급';

-- -- ========== TBL_MEMBER_TMP ==========
-- ALTER TABLE COTDL.TBL_MEMBER_TMP ADD (TELNO VARCHAR2(20));
-- ALTER TABLE COTDL.TBL_MEMBER_TMP ADD (GRADE VARCHAR2(20));
-- ALTER TABLE COTDL.TBL_MEMBER_TMP ADD (EMAIL VARCHAR2(200));
-- ALTER TABLE COTDL.TBL_MEMBER_TMP ADD (MANAGER_ID VARCHAR2(50));
-- ALTER TABLE COTDL.TBL_MEMBER_TMP ADD (POSITION VARCHAR2(50));
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_TMP.TELNO IS '전화번호';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_TMP.GRADE IS '등급';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_TMP.EMAIL IS '이메일';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_TMP.MANAGER_ID IS '상위결재자 ID';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_TMP.POSITION IS '직위/직급';

-- -- ========== TBL_MEMBER_NEW ==========
-- ALTER TABLE COTDL.TBL_MEMBER_NEW ADD (TELNO VARCHAR2(20));
-- ALTER TABLE COTDL.TBL_MEMBER_NEW ADD (GRADE VARCHAR2(20));
-- ALTER TABLE COTDL.TBL_MEMBER_NEW ADD (EMAIL VARCHAR2(200));
-- ALTER TABLE COTDL.TBL_MEMBER_NEW ADD (MANAGER_ID VARCHAR2(50));
-- ALTER TABLE COTDL.TBL_MEMBER_NEW ADD (POSITION VARCHAR2(50));
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_NEW.TELNO IS '전화번호';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_NEW.GRADE IS '등급';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_NEW.EMAIL IS '이메일';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_NEW.MANAGER_ID IS '상위결재자 ID';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_NEW.POSITION IS '직위/직급';

-- -- ========== TBL_MEMBER_OLD ==========
-- ALTER TABLE COTDL.TBL_MEMBER_OLD ADD (TELNO VARCHAR2(20));
-- ALTER TABLE COTDL.TBL_MEMBER_OLD ADD (GRADE VARCHAR2(20));
-- ALTER TABLE COTDL.TBL_MEMBER_OLD ADD (EMAIL VARCHAR2(200));
-- ALTER TABLE COTDL.TBL_MEMBER_OLD ADD (MANAGER_ID VARCHAR2(50));
-- ALTER TABLE COTDL.TBL_MEMBER_OLD ADD (POSITION VARCHAR2(50));
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_OLD.TELNO IS '전화번호';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_OLD.GRADE IS '등급';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_OLD.EMAIL IS '이메일';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_OLD.MANAGER_ID IS '상위결재자 ID';
-- COMMENT ON COLUMN COTDL.TBL_MEMBER_OLD.POSITION IS '직위/직급';
