-- ============================================================
-- [테스트] 인사시스템 사용자 원천 테이블 (Oracle)
-- 배치잡 DLM_JOB_BATCH_MEMBER 테스트용
-- ============================================================

-- DDL
CREATE TABLE COOWNER.TB_HR_USER_INFO (
    EMP_NO       VARCHAR2(50)  NOT NULL,
    EMP_NM       VARCHAR2(64)  NOT NULL,
    DEPT_CD      VARCHAR2(20),
    DEPT_NM      VARCHAR2(50),
    TEL_NO       VARCHAR2(20),
    GRADE_NM     VARCHAR2(20),
    EMAIL        VARCHAR2(200),
    MGR_EMP_NO   VARCHAR2(50),
    POSITION_NM  VARCHAR2(50),
    USE_YN       CHAR(1) DEFAULT 'Y',
    CONSTRAINT PK_TB_HR_USER_INFO PRIMARY KEY (EMP_NO)
);

COMMENT ON TABLE  COOWNER.TB_HR_USER_INFO IS '[테스트] 인사시스템 사용자 원천';
COMMENT ON COLUMN COOWNER.TB_HR_USER_INFO.EMP_NO      IS '사번';
COMMENT ON COLUMN COOWNER.TB_HR_USER_INFO.EMP_NM      IS '성명';
COMMENT ON COLUMN COOWNER.TB_HR_USER_INFO.DEPT_CD     IS '부서코드';
COMMENT ON COLUMN COOWNER.TB_HR_USER_INFO.DEPT_NM     IS '부서명';
COMMENT ON COLUMN COOWNER.TB_HR_USER_INFO.TEL_NO      IS '전화번호';
COMMENT ON COLUMN COOWNER.TB_HR_USER_INFO.GRADE_NM    IS '등급';
COMMENT ON COLUMN COOWNER.TB_HR_USER_INFO.EMAIL       IS '이메일';
COMMENT ON COLUMN COOWNER.TB_HR_USER_INFO.MGR_EMP_NO  IS '상위결재자 사번';
COMMENT ON COLUMN COOWNER.TB_HR_USER_INFO.POSITION_NM IS '직위';
COMMENT ON COLUMN COOWNER.TB_HR_USER_INFO.USE_YN      IS '사용여부 (Y/N)';


-- TEST DATA
INSERT INTO COOWNER.TB_HR_USER_INFO (EMP_NO, EMP_NM, DEPT_CD, DEPT_NM, TEL_NO, GRADE_NM, EMAIL, MGR_EMP_NO, POSITION_NM, USE_YN)
VALUES ('park01', '박관리', 'IT00', 'IT본부', '010-4444-4444', '1', 'park@example.com', NULL, '본부장', 'Y');

INSERT INTO COOWNER.TB_HR_USER_INFO (EMP_NO, EMP_NM, DEPT_CD, DEPT_NM, TEL_NO, GRADE_NM, EMAIL, MGR_EMP_NO, POSITION_NM, USE_YN)
VALUES ('kim01', '김보안', 'IT01', '정보보안팀', '010-2222-2222', '2', 'kimbo@example.com', 'park01', '팀장', 'Y');

INSERT INTO COOWNER.TB_HR_USER_INFO (EMP_NO, EMP_NM, DEPT_CD, DEPT_NM, TEL_NO, GRADE_NM, EMAIL, MGR_EMP_NO, POSITION_NM, USE_YN)
VALUES ('hong01', '홍길동', 'IT01', '정보보안팀', '010-1111-1111', '3', 'hong@example.com', 'kim01', '부서장', 'Y');

INSERT INTO COOWNER.TB_HR_USER_INFO (EMP_NO, EMP_NM, DEPT_CD, DEPT_NM, TEL_NO, GRADE_NM, EMAIL, MGR_EMP_NO, POSITION_NM, USE_YN)
VALUES ('seo01', '서운영', 'IT01', '정보보안팀', '010-1010-1010', '3', 'seo@example.com', 'kim01', '사원', 'Y');

INSERT INTO COOWNER.TB_HR_USER_INFO (EMP_NO, EMP_NM, DEPT_CD, DEPT_NM, TEL_NO, GRADE_NM, EMAIL, MGR_EMP_NO, POSITION_NM, USE_YN)
VALUES ('lee01', '이데이터', 'IT02', '데이터관리팀', '010-3333-3333', '3', 'lee@example.com', 'park01', '대리', 'Y');

INSERT INTO COOWNER.TB_HR_USER_INFO (EMP_NO, EMP_NM, DEPT_CD, DEPT_NM, TEL_NO, GRADE_NM, EMAIL, MGR_EMP_NO, POSITION_NM, USE_YN)
VALUES ('choi01', '최개발', 'IT02', '데이터관리팀', '010-5555-5555', '3', 'choi@example.com', 'lee01', '사원', 'Y');

INSERT INTO COOWNER.TB_HR_USER_INFO (EMP_NO, EMP_NM, DEPT_CD, DEPT_NM, TEL_NO, GRADE_NM, EMAIL, MGR_EMP_NO, POSITION_NM, USE_YN)
VALUES ('yoon01', '윤기획', 'BIZ01', '경영기획팀', '010-7777-7777', '1', 'yoon@example.com', NULL, '팀장', 'Y');

INSERT INTO COOWNER.TB_HR_USER_INFO (EMP_NO, EMP_NM, DEPT_CD, DEPT_NM, TEL_NO, GRADE_NM, EMAIL, MGR_EMP_NO, POSITION_NM, USE_YN)
VALUES ('jung01', '정분석', 'BIZ01', '경영기획팀', '010-6666-6666', '2', 'jung@example.com', 'yoon01', '과장', 'Y');

INSERT INTO COOWNER.TB_HR_USER_INFO (EMP_NO, EMP_NM, DEPT_CD, DEPT_NM, TEL_NO, GRADE_NM, EMAIL, MGR_EMP_NO, POSITION_NM, USE_YN)
VALUES ('kang01', '강감사', 'AUD01', '감사팀', '010-8888-8888', '2', 'kang@example.com', NULL, '팀장', 'Y');

INSERT INTO COOWNER.TB_HR_USER_INFO (EMP_NO, EMP_NM, DEPT_CD, DEPT_NM, TEL_NO, GRADE_NM, EMAIL, MGR_EMP_NO, POSITION_NM, USE_YN)
VALUES ('shin01', '신컴플', 'AUD01', '감사팀', '010-9999-9999', '3', 'shin@example.com', 'kang01', '대리', 'Y');

INSERT INTO COOWNER.TB_HR_USER_INFO (EMP_NO, EMP_NM, DEPT_CD, DEPT_NM, TEL_NO, GRADE_NM, EMAIL, MGR_EMP_NO, POSITION_NM, USE_YN)
VALUES ('ex01', '퇴사자A', 'IT01', '정보보안팀', '010-0000-0000', '3', 'ex01@example.com', 'kim01', '사원', 'N');

COMMIT;
