#Mariadb.................................
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://192.168.0.7:3306/bootex?
#&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
#spring.datasource.username=bootuser
#spring.datasource.password=bootuser

#Oracle.................................
#spring.datasource.driver-class-name==net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.datasource.jdbc-url=jdbc:log4jdbc:oracle:thin:@192.168.0.7:1521:XE
#spring.dataSource.username=cotdl
#spring.dataSource.password=cotdl22

spring.datasource.jndi-name: jndi/dlmhome
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@192.168.0.7:1521:XE
#spring.datasource.username=cotdl
#spring.datasource.password=cotdl22

spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=10000
spring.datasource.hikari.maximum-pool-size=8

# MyBatis.................................
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=datablocks.dlm.mapper
logging.level.com.atoz_develop.mybatissample.repository=TRACE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

server.servlet.jsp.init-parameters.development=true

#Tomcat.................................  java -Xms2048m -Xmx4096m -jar jarFileName.jar
server.port=8088
server.compression.enabled=true
server.tomcat.accesslog.enabled=true
server.tomcat.basedir=.
server.tomcat.accesslog.directory=logs
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.prefix=access_log
server.tomcat.accesslog.file-date-format=.yyyy-MM-dd
#server.tomcat.accesslog.pattern=common #일반적인 access log 포맷 적용시 \
server.tomcat.accesslog.pattern=%{yyyy-MM-dd HH:mm:ss}t %s %r %{User-Agent}i %{Referer}i %a %b %D

#keytool -genkey -alias dlm-keystore -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore dlm-keystore.p12 -validity 3650
server.ssl.enabled=false
server.ssl.key-alias=dlm-keystore
server.ssl.key-password=dlmssl
server.ssl.key-store=classpath:dlm-keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=dlmssl
kserver.ssl.ey-store-provider=SUN

#Multipart.................................
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=./upload
spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.max-file-size=10MB

#Logging.................................
# application.properties in 'src/main/resources'  그냥 jar를 실행하는 폴더에 application.properties 파일을 두고 거기에 처음에 설명한 것처럼 외부 설정파일을 지정하면 된다. jar 외부에 있는 application.properties 파일이 더 우선순위가 높기 때문에 그곳에 지정한 파일이 적용된다.

#java -jar -Dspring.profiles.active=prod
#spring.profiles.active = prod
spring.profiles.active=local
logging.config=classpath:logback-${spring.profiles.active}.xml

#- 참고 순서
#1) classpath(resources디렉토리 밑)에 logback-spring.xml파일이 있으면 설정파일을 읽어간다.
#2) logback-spring.xml파일이 없다면 .yml(.properties)파일의 설정을 읽어간다.
#3) logback-spring.xml파일과 .yml(.properties)파일이 동시에 있으면 .yml(.properties) 설정 파일을 적용 후 xml파일이 적용된다

#logging.level.root=warn
#logging.level.org.springframework.web=debug
#logging.level.org.hibernate=error
##ogging.level.org.hibernate=debug
#logging.level.org.springframework.security.web= warn



