-- ==========================================================================
-- COTDL 전체 테이블 DDL (MySQL/MariaDB)
-- 생성일: 2026-03-22
-- 소스: 0.X-One_MANAGER.xlsx > TABLE_DEF
-- 테이블 수: 80
-- ==========================================================================
--
-- [변경이력]
-- 2026-03-26  TBL_PIIEXTRACT_PURGE_STAT 신규 추가
--             - tbl_piiextract 영구파기/복원 완료 레코드 퍼지 시 보고서 통계 보존용
--             - 주간 자동 퍼지(매주 일요일 03:00) 도입에 따른 통계 스냅샷 테이블
-- 2026-03-26  TBL_PIIEXTRACT_PURGE_LOG 신규 추가
--             - 퍼지된 고객별 파기 증적 (개인정보 제외, CUSTID+파기일시만 보존)
--             - 감사/민원 시 "특정 고객이 언제 파기됐는지" 개별 추적용
--             - 적용 방법: TBL_PIIEXTRACT_PURGE_STAT, TBL_PIIEXTRACT_PURGE_LOG CREATE TABLE 구문 실행
-- 2026-03-26  TBL_PIIORDER 비-파기 Job 실행 이력 퍼지 기능 추가
--             - TBL_PIIORDER + 하위 8개 테이블 (ORDERSTEP, ORDERSTEPTABLE, ORDERTHREAD,
--               ORDERJOBWAIT, ORDERSTEPTABLEWAIT, ORDERSTEPTABLEUPDATE, INNERSTEP, ORDERDDL) 대상
--             - jobtype='PII', ARC_DATA_DELETE, RESTORE_CUSTID 제외, 6개월 경과 완료 오더 삭제
--             - DDL 변경 없음 (기존 테이블에서 DELETE만 수행)
-- 2026-03-30  TBL_METATABLE_TMP, TBL_METATABLE_OLD, TBL_METATABLE_NEW  DROP&CREATE 다시 해야함.
-- ==========================================================================

-- ------------------------------------------------------------
-- TBL_MEMBER
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_MEMBER`;
CREATE TABLE `COTDL`.`TBL_MEMBER` (
  `USERID` VARCHAR(50) NOT NULL,
  `USERPW` VARCHAR(100) NOT NULL,
  `USERNAME` VARCHAR(64) NOT NULL,
  `REGDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATEDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `ENABLED` CHAR(1) DEFAULT '1',
  `DEPT_CD` VARCHAR(20) NOT NULL,
  `DEPT_NAME` VARCHAR(50) NOT NULL,
  `TELNO` VARCHAR(20) NOT NULL,
  `GRADE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_MEMBER_AUTH
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_MEMBER_AUTH`;
CREATE TABLE `COTDL`.`TBL_MEMBER_AUTH` (
  `USERID` VARCHAR(50) NOT NULL,
  `AUTH` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`USERID`, `AUTH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIDATABASE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIDATABASE`;
CREATE TABLE `COTDL`.`TBL_PIIDATABASE` (
  `DB` VARCHAR(100) NOT NULL,
  `SYSTEM` VARCHAR(30) NOT NULL,
  `ENV` VARCHAR(30) NOT NULL,
  `DBTYPE` VARCHAR(30) NOT NULL,
  `DBUSER` VARCHAR(30) NOT NULL,
  `PWD` VARCHAR(256) NOT NULL,
  `HOSTNAME` VARCHAR(30) NOT NULL,
  `PORT` VARCHAR(10) NOT NULL,
  `ID_TYPE` VARCHAR(15),
  `ID` VARCHAR(15),
  `COMMENTS` VARCHAR(500),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  PRIMARY KEY (`DB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIICONFTABLE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIICONFTABLE`;
CREATE TABLE `COTDL`.`TBL_PIICONFTABLE` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `PAGITYPE` VARCHAR(10),
  `PAGITYPEDETAIL` VARCHAR(10),
  `ARCHIVEFLAG` VARCHAR(1),
  `STATUS` VARCHAR(30),
  `PRECEDING` VARCHAR(30),
  `SUCCEDDING` VARCHAR(30),
  `SEQ1` INT,
  `SEQ2` INT,
  `SEQ3` INT,
  `PIPELINE` INT,
  `PK_COLUMNS` VARCHAR(200),
  `PK_DATA_TYPE` VARCHAR(20),
  `IMATABLE_NAME` VARCHAR(128),
  `MASTERKEY` VARCHAR(30),
  `WHERE_COL` VARCHAR(200),
  `WHERE_KEY_NAME` VARCHAR(100),
  `PARALLELCNT` INT,
  `TOTALCNT` INT,
  `WHERESTR` TEXT,
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIICONFKEYMAP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIICONFKEYMAP`;
CREATE TABLE `COTDL`.`TBL_PIICONFKEYMAP` (
  `KEYMAP_ID` VARCHAR(50) NOT NULL,
  `KEY_NAME` VARCHAR(100) NOT NULL,
  `DB` VARCHAR(30) NOT NULL,
  `SEQ1` INT NOT NULL,
  `SEQ2` INT NOT NULL,
  `SEQ3` INT NOT NULL,
  `KEY_COLS` VARCHAR(200),
  `SRC_OWNER` VARCHAR(128),
  `SRC_TABLE_NAME` VARCHAR(128),
  `WHERE_COL` VARCHAR(200),
  `WHERE_KEY_NAME` VARCHAR(100),
  `PARALLELCNT` INT,
  `STATUS` VARCHAR(30),
  `SQLTYPE` VARCHAR(10),
  `INSERTSTR` VARCHAR(1000),
  `WHERESTR` TEXT,
  `REFSTR` VARCHAR(500),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  PRIMARY KEY (`KEYMAP_ID`, `KEY_NAME`, `DB`, `SEQ1`, `SEQ2`, `SEQ3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIKEYMAP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIKEYMAP`;
CREATE TABLE `COTDL`.`TBL_PIIKEYMAP` (
  `KEYMAP_ID` VARCHAR(50),
  `DB` VARCHAR(30),
  `KEY_NAME` VARCHAR(50),
  `BASEDATE` DATETIME,
  `CUSTID` VARCHAR(50),
  `EXPECTED_ARC_DEL_DATE` DATETIME,
  `VAL1` VARCHAR(255),
  `VAL2` VARCHAR(255),
  `VAL3` VARCHAR(255),
  `VAL4` VARCHAR(255),
  `VAL5` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIKEYMAP_TMP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIKEYMAP_TMP`;
CREATE TABLE `COTDL`.`TBL_PIIKEYMAP_TMP` (
  `KEYMAP_ID` VARCHAR(50),
  `DB` VARCHAR(30),
  `KEY_NAME` VARCHAR(50),
  `BASEDATE` DATETIME,
  `CUSTID` VARCHAR(50),
  `EXPECTED_ARC_DEL_DATE` DATETIME,
  `VAL1` VARCHAR(255),
  `VAL2` VARCHAR(255),
  `VAL3` VARCHAR(255),
  `VAL4` VARCHAR(255),
  `VAL5` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIKEYMAP_HIST
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIKEYMAP_HIST`;
CREATE TABLE `COTDL`.`TBL_PIIKEYMAP_HIST` (
  `KEYMAP_ID` VARCHAR(50),
  `DB` VARCHAR(30),
  `KEY_NAME` VARCHAR(50),
  `BASEDATE` DATETIME,
  `CUSTID` VARCHAR(50),
  `EXPECTED_ARC_DEL_DATE` DATETIME,
  `VAL1` VARCHAR(255),
  `VAL2` VARCHAR(255),
  `VAL3` VARCHAR(255),
  `VAL4` VARCHAR(255),
  `VAL5` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIJOB
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIJOB`;
CREATE TABLE `COTDL`.`TBL_PIIJOB` (
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `JOBNAME` VARCHAR(100) NOT NULL,
  `SYSTEM` VARCHAR(50),
  `POLICY_ID` VARCHAR(50),
  `KEYMAP_ID` VARCHAR(50),
  `JOBTYPE` VARCHAR(20) NOT NULL,
  `RUNTYPE` VARCHAR(20) NOT NULL,
  `CALENDAR` VARCHAR(20) NOT NULL,
  `TIME` VARCHAR(20),
  `CRONVAL` VARCHAR(10),
  `CONFIRMFLAG` VARCHAR(1),
  `STATUS` VARCHAR(30) NOT NULL,
  `PHASE` VARCHAR(30) NOT NULL,
  `JOB_OWNER_ID1` VARCHAR(30) NOT NULL,
  `JOB_OWNER_NAME1` VARCHAR(30) NOT NULL,
  `JOB_OWNER_ID2` VARCHAR(30),
  `JOB_OWNER_NAME2` VARCHAR(30),
  `JOB_OWNER_ID3` VARCHAR(30),
  `JOB_OWNER_NAME3` VARCHAR(30),
  `ENDDATE` DATETIME,
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  PRIMARY KEY (`JOBID`, `VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIISTEP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIISTEP`;
CREATE TABLE `COTDL`.`TBL_PIISTEP` (
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `STEPID` VARCHAR(100) NOT NULL,
  `STEPNAME` VARCHAR(100) NOT NULL,
  `STEPTYPE` VARCHAR(20) NOT NULL,
  `STEPSEQ` INT NOT NULL,
  `DB` VARCHAR(100) NOT NULL,
  `STATUS` VARCHAR(30),
  `PHASE` VARCHAR(30) NOT NULL,
  `THREADCNT` INT,
  `COMMITCNT` INT,
  `ENDDATE` DATETIME,
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  `DATA_HANDLING_METHOD` VARCHAR(30),
  `PROCESSING_METHOD` VARCHAR(30),
  `FK_DISABLE_FLAG` VARCHAR(1),
  `INDEX_UNUSUAL_FLAG` VARCHAR(2),
  `VAL1` VARCHAR(10),
  `VAL2` VARCHAR(10),
  `VAL3` VARCHAR(10),
  `VAL4` VARCHAR(10),
  `VAL5` VARCHAR(10),
  PRIMARY KEY (`JOBID`, `VERSION`, `STEPID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIISTEPTABLE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIISTEPTABLE`;
CREATE TABLE `COTDL`.`TBL_PIISTEPTABLE` (
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `STEPID` VARCHAR(100) NOT NULL,
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `PAGITYPE` VARCHAR(10),
  `PAGITYPEDETAIL` VARCHAR(10),
  `EXETYPE` VARCHAR(10) NOT NULL,
  `ARCHIVEFLAG` VARCHAR(1),
  `STATUS` VARCHAR(30),
  `PRECEDING` VARCHAR(30),
  `SUCCEDDING` VARCHAR(30),
  `SEQ1` INT NOT NULL,
  `SEQ2` INT NOT NULL,
  `SEQ3` INT NOT NULL,
  `PIPELINE` INT,
  `PK_COL` VARCHAR(200),
  `WHERE_COL` VARCHAR(200),
  `WHERE_KEY_NAME` VARCHAR(50),
  `PARALLELCNT` INT,
  `COMMITCNT` INT,
  `WHERESTR` TEXT,
  `SQLSTR` TEXT,
  `KEYMAP_ID` VARCHAR(50),
  `KEY_NAME` VARCHAR(50),
  `KEY_COLS` VARCHAR(200),
  `KEY_REFSTR` VARCHAR(500),
  `SQLTYPE` VARCHAR(10),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  `HINTSELECT` VARCHAR(100),
  `HINTINSERT` VARCHAR(100),
  `UVAL1` VARCHAR(100),
  `UVAL2` VARCHAR(100),
  `UVAL3` VARCHAR(100),
  `UVAL4` VARCHAR(100),
  `UVAL5` VARCHAR(100),
  PRIMARY KEY (`JOBID`, `VERSION`, `STEPID`, `SEQ1`, `SEQ2`, `SEQ3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIJOBWAIT
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIJOBWAIT`;
CREATE TABLE `COTDL`.`TBL_PIIJOBWAIT` (
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `TYPE` VARCHAR(15) NOT NULL DEFAULT 'PRE',
  `JOBID_W` VARCHAR(200) NOT NULL,
  `JOBNAME_W` VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIISTEPTABLEWAIT
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIISTEPTABLEWAIT`;
CREATE TABLE `COTDL`.`TBL_PIISTEPTABLEWAIT` (
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `STEPID` VARCHAR(100) NOT NULL,
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `TYPE` VARCHAR(15) NOT NULL,
  `DB_W` VARCHAR(100) NOT NULL,
  `OWNER_W` VARCHAR(128) NOT NULL,
  `TABLE_NAME_W` VARCHAR(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIORDERJOBWAIT
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIORDERJOBWAIT`;
CREATE TABLE `COTDL`.`TBL_PIIORDERJOBWAIT` (
  `ORDERID` INT NOT NULL,
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `TYPE` VARCHAR(15) NOT NULL,
  `JOBID_W` VARCHAR(200) NOT NULL,
  `JOBNAME_W` VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIORDERSTEPTABLEWAIT
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIORDERSTEPTABLEWAIT`;
CREATE TABLE `COTDL`.`TBL_PIIORDERSTEPTABLEWAIT` (
  `ORDERID` INT NOT NULL,
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `STEPID` VARCHAR(100) NOT NULL,
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `TYPE` VARCHAR(15) NOT NULL,
  `DB_W` VARCHAR(100) NOT NULL,
  `OWNER_W` VARCHAR(128) NOT NULL,
  `TABLE_NAME_W` VARCHAR(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIITABLE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIITABLE`;
CREATE TABLE `COTDL`.`TBL_PIITABLE` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_ID` INT NOT NULL,
  `PK_YN` VARCHAR(1),
  `PK_POSITION` INT,
  `FULL_DATA_TYPE` VARCHAR(100),
  `DATA_TYPE` VARCHAR(100) NOT NULL,
  `DATA_LENGTH` BIGINT,
  `NULLABLE` VARCHAR(1),
  `COMMENTS` VARCHAR(255),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIITABLE_TMP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIITABLE_TMP`;
CREATE TABLE `COTDL`.`TBL_PIITABLE_TMP` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_ID` INT NOT NULL,
  `PK_YN` VARCHAR(1),
  `PK_POSITION` INT,
  `FULL_DATA_TYPE` VARCHAR(100),
  `DATA_TYPE` VARCHAR(100) NOT NULL,
  `DATA_LENGTH` INT,
  `NULLABLE` VARCHAR(1),
  `COMMENTS` VARCHAR(255),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIITABLE_NEW
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIITABLE_NEW`;
CREATE TABLE `COTDL`.`TBL_PIITABLE_NEW` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_ID` INT NOT NULL,
  `PK_YN` VARCHAR(1),
  `PK_POSITION` INT,
  `FULL_DATA_TYPE` VARCHAR(100),
  `DATA_TYPE` VARCHAR(100) NOT NULL,
  `DATA_LENGTH` INT,
  `NULLABLE` VARCHAR(1),
  `COMMENTS` VARCHAR(255),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIITABLE_OLD
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIITABLE_OLD`;
CREATE TABLE `COTDL`.`TBL_PIITABLE_OLD` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_ID` INT NOT NULL,
  `PK_YN` VARCHAR(1),
  `PK_POSITION` INT,
  `FULL_DATA_TYPE` VARCHAR(100),
  `DATA_TYPE` VARCHAR(100) NOT NULL,
  `DATA_LENGTH` INT,
  `NULLABLE` VARCHAR(1),
  `COMMENTS` VARCHAR(255),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIAPPROVAL
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIAPPROVAL`;
CREATE TABLE `COTDL`.`TBL_PIIAPPROVAL` (
  `APPROVALID` VARCHAR(50) NOT NULL,
  `APPROVALNAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`APPROVALID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIAPPROVALLINE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIAPPROVALLINE`;
CREATE TABLE `COTDL`.`TBL_PIIAPPROVALLINE` (
  `APRVLINEID` VARCHAR(100) NOT NULL,
  `APPROVALID` VARCHAR(50) NOT NULL,
  `APPROVALNAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`APRVLINEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIAPPROVALSTEP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIAPPROVALSTEP`;
CREATE TABLE `COTDL`.`TBL_PIIAPPROVALSTEP` (
  `APRVLINEID` VARCHAR(100) NOT NULL,
  `SEQ` INT NOT NULL,
  `STEPNAME` VARCHAR(50) NOT NULL,
  `APPROVALID` VARCHAR(50) NOT NULL,
  `APPROVALNAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`APRVLINEID`, `SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIAPPROVALUSER
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIAPPROVALUSER`;
CREATE TABLE `COTDL`.`TBL_PIIAPPROVALUSER` (
  `APRVLINEID` VARCHAR(100) NOT NULL,
  `SEQ` INT NOT NULL,
  `STEPNAME` VARCHAR(50) NOT NULL,
  `APPROVERID` VARCHAR(30) NOT NULL,
  `APPROVERNAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`APRVLINEID`, `SEQ`, `APPROVERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIAPPROVALREQ
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIAPPROVALREQ`;
CREATE TABLE `COTDL`.`TBL_PIIAPPROVALREQ` (
  `REQID` INT NOT NULL,
  `APRVLINEID` VARCHAR(100) NOT NULL,
  `SEQ` INT NOT NULL,
  `APPROVALID` VARCHAR(50) NOT NULL,
  `PHASE` VARCHAR(30) NOT NULL,
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10),
  `REQUESTERID` VARCHAR(30),
  `REQUESTERNAME` VARCHAR(30),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REQREASON` VARCHAR(4000),
  PRIMARY KEY (`REQID`, `APRVLINEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIAPPROVALSTEPREQ
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIAPPROVALSTEPREQ`;
CREATE TABLE `COTDL`.`TBL_PIIAPPROVALSTEPREQ` (
  `REQID` INT NOT NULL,
  `APRVLINEID` VARCHAR(100) NOT NULL,
  `SEQ` INT NOT NULL,
  `STEPNAME` VARCHAR(50) NOT NULL,
  `STATUS` VARCHAR(30) NOT NULL,
  `APPROVERID` VARCHAR(30) NOT NULL,
  `APPROVERNAME` VARCHAR(30) NOT NULL,
  `REGDATE` DATETIME,
  `COMMENT` VARCHAR(4000),
  PRIMARY KEY (`REQID`, `APRVLINEID`, `SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIORDER
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIORDER`;
CREATE TABLE `COTDL`.`TBL_PIIORDER` (
  `ORDERID` INT NOT NULL,
  `BASEDATE` DATETIME NOT NULL,
  `RUNCNT` INT,
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `JOBNAME` VARCHAR(100) NOT NULL,
  `SYSTEM` VARCHAR(50),
  `POLICY_ID` VARCHAR(50),
  `KEYMAP_ID` VARCHAR(50),
  `JOBTYPE` VARCHAR(20),
  `RUNTYPE` VARCHAR(20),
  `CALENDAR` VARCHAR(20),
  `TIME` VARCHAR(20),
  `STATUS` VARCHAR(30),
  `CONFIRMFLAG` VARCHAR(1),
  `HOLDFLAG` VARCHAR(1),
  `FORCEOKFLAG` VARCHAR(1),
  `KILLFLAG` VARCHAR(1),
  `ESTSTARTTIME` DATETIME,
  `RUNNINGTIME` VARCHAR(20),
  `REALSTARTTIME` DATETIME,
  `REALENDTIME` DATETIME,
  `JOB_OWNER_ID1` VARCHAR(30),
  `JOB_OWNER_NAME1` VARCHAR(30),
  `JOB_OWNER_ID2` VARCHAR(30),
  `JOB_OWNER_NAME2` VARCHAR(30),
  `JOB_OWNER_ID3` VARCHAR(30),
  `JOB_OWNER_NAME3` VARCHAR(30),
  `ORDERDATE` DATETIME,
  `ORDERUSERID` VARCHAR(10),
  PRIMARY KEY (`ORDERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIORDERSTEP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIORDERSTEP`;
CREATE TABLE `COTDL`.`TBL_PIIORDERSTEP` (
  `ORDERID` INT NOT NULL,
  `STATUS` VARCHAR(30),
  `CONFIRMFLAG` VARCHAR(1),
  `HOLDFLAG` VARCHAR(1),
  `FORCEOKFLAG` VARCHAR(1),
  `KILLFLAG` VARCHAR(1),
  `BASEDATE` DATETIME NOT NULL,
  `THREADCNT` INT,
  `COMMITCNT` INT,
  `RUNCNT` INT,
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `STEPID` VARCHAR(100) NOT NULL,
  `STEPNAME` VARCHAR(100),
  `STEPTYPE` VARCHAR(20),
  `STEPSEQ` INT,
  `DB` VARCHAR(100),
  `TOTALTABCNT` INT,
  `SUCCESSTABCNT` INT,
  `RUNNINGTIME` VARCHAR(20),
  `REALSTARTTIME` DATETIME,
  `REALENDTIME` DATETIME,
  `ORDERUSERID` VARCHAR(10),
  `DATA_HANDLING_METHOD` VARCHAR(30),
  `PROCESSING_METHOD` VARCHAR(30),
  `FK_DISABLE_FLAG` VARCHAR(1),
  `INDEX_UNUSUAL_FLAG` VARCHAR(2),
  `VAL1` VARCHAR(10),
  `VAL2` VARCHAR(10),
  `VAL3` VARCHAR(10),
  `VAL4` VARCHAR(10),
  `VAL5` VARCHAR(10),
  PRIMARY KEY (`ORDERID`, `JOBID`, `VERSION`, `STEPID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIORDERSTEPTABLE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIORDERSTEPTABLE`;
CREATE TABLE `COTDL`.`TBL_PIIORDERSTEPTABLE` (
  `ORDERID` INT NOT NULL,
  `STATUS` VARCHAR(30),
  `FORCEOKFLAG` VARCHAR(1),
  `BASEDATE` DATETIME NOT NULL,
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `STEPID` VARCHAR(100) NOT NULL,
  `STEPNAME` VARCHAR(100) NOT NULL,
  `STEPTYPE` VARCHAR(20) NOT NULL,
  `STEPSEQ` INT NOT NULL,
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `PAGITYPE` VARCHAR(10),
  `PAGITYPEDETAIL` VARCHAR(10),
  `EXETYPE` VARCHAR(10),
  `ARCHIVEFLAG` VARCHAR(1),
  `PRECEDING` VARCHAR(30),
  `SUCCEDDING` VARCHAR(30),
  `SEQ1` INT NOT NULL,
  `SEQ2` INT NOT NULL,
  `SEQ3` INT NOT NULL,
  `PIPELINE` INT,
  `PK_COL` VARCHAR(200),
  `WHERE_COL` VARCHAR(200),
  `WHERE_KEY_NAME` VARCHAR(50),
  `PARALLELCNT` INT,
  `COMMITCNT` INT,
  `WHERESTR` TEXT,
  `SQLSTR` TEXT,
  `ARCCNT` INT,
  `ARCTIME` VARCHAR(20),
  `ARCSTART` DATETIME,
  `ARCEND` DATETIME,
  `EXECNT` BIGINT,
  `EXETIME` VARCHAR(20),
  `EXESTART` DATETIME,
  `EXEEND` DATETIME,
  `SQLMSG` VARCHAR(4000),
  `HINTSELECT` VARCHAR(100),
  `HINTINSERT` VARCHAR(100),
  `UVAL1` VARCHAR(100),
  `UVAL2` VARCHAR(100),
  `UVAL3` VARCHAR(100),
  `UVAL4` VARCHAR(100),
  `UVAL5` VARCHAR(100),
  PRIMARY KEY (`ORDERID`, `STEPID`, `SEQ1`, `SEQ2`, `SEQ3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIORDERTHREAD
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIORDERTHREAD`;
CREATE TABLE `COTDL`.`TBL_PIIORDERTHREAD` (
  `ORDERID` INT NOT NULL,
  `JOBID` VARCHAR(200),
  `VERSION` VARCHAR(10),
  `STEPID` VARCHAR(100) NOT NULL,
  `SEQ1` INT NOT NULL,
  `SEQ2` INT NOT NULL,
  `SEQ3` INT NOT NULL,
  `STATUS` VARCHAR(30),
  `EXESTART` DATETIME,
  PRIMARY KEY (`ORDERID`, `STEPID`, `SEQ1`, `SEQ2`, `SEQ3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIRESTORE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIRESTORE`;
CREATE TABLE `COTDL`.`TBL_PIIRESTORE` (
  `RESTOREID` INT NOT NULL,
  `PHASE` VARCHAR(15),
  `APPLY_TYPE` VARCHAR(30),
  `OLD_ORDERID` INT,
  `NEW_ORDERID` INT,
  `KEYMAP_ID` VARCHAR(50),
  `BASEDATE` DATETIME,
  `CUSTID` VARCHAR(50),
  `CUST_NM` VARCHAR(50),
  `BIRTH_DT` VARCHAR(8),
  `RSDNT_ALTRNTV_ID` VARCHAR(13),
  `CUST_PIN` VARCHAR(128),
  `OLD_JOBID` VARCHAR(200),
  `OLD_VERSION` VARCHAR(10),
  `NEW_JOBID` VARCHAR(200),
  `STATUS` VARCHAR(30),
  `BROWSE_DEADLINE_DT` DATETIME,
  `APPROVE_DATE` DATETIME,
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  PRIMARY KEY (`RESTOREID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIRECOVERY
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIRECOVERY`;
CREATE TABLE `COTDL`.`TBL_PIIRECOVERY` (
  `RECOVERYID` INT NOT NULL,
  `PHASE` VARCHAR(30) NOT NULL,
  `OLD_ORDERID` INT,
  `NEW_ORDERID` INT,
  `KEYMAP_ID` VARCHAR(50),
  `BASEDATE` DATETIME,
  `OLD_JOBID` VARCHAR(200),
  `OLD_VERSION` VARCHAR(10),
  `NEW_JOBID` VARCHAR(200),
  `STATUS` VARCHAR(30),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  PRIMARY KEY (`RECOVERYID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- PERSISTENT_LOGINS
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`PERSISTENT_LOGINS`;
CREATE TABLE `COTDL`.`PERSISTENT_LOGINS` (
  `USERNAME` VARCHAR(64) NOT NULL,
  `SERIES` VARCHAR(64) NOT NULL,
  `TOKEN` VARCHAR(64) NOT NULL,
  `LAST_USED` DATETIME NOT NULL,
  PRIMARY KEY (`SERIES`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIICODEMASTER
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIICODEMASTER`;
CREATE TABLE `COTDL`.`TBL_PIICODEMASTER` (
  `CODE_ID` VARCHAR(50) NOT NULL,
  `CODE_NAME` VARCHAR(50) NOT NULL,
  `CODE_NAME_EN` VARCHAR(100) NOT NULL,
  `CODE_ID_PARENT` VARCHAR(1),
  PRIMARY KEY (`CODE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIICODE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIICODE`;
CREATE TABLE `COTDL`.`TBL_PIICODE` (
  `CODE_ID` VARCHAR(50) NOT NULL,
  `CODE` VARCHAR(50) NOT NULL,
  `VALUE` VARCHAR(100) NOT NULL,
  `USE_FLAG` VARCHAR(1) NOT NULL,
  `SEQ` INT NOT NULL,
  PRIMARY KEY (`CODE_ID`, `CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIISYSTEM
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIISYSTEM`;
CREATE TABLE `COTDL`.`TBL_PIISYSTEM` (
  `SYSTEM_ID` VARCHAR(50) NOT NULL,
  `SYSTEM_NAME` VARCHAR(50) NOT NULL,
  `SYSTEM_INFO` VARCHAR(200) NOT NULL,
  `USE_FLAG` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`SYSTEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIPOLICY
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIPOLICY`;
CREATE TABLE `COTDL`.`TBL_PIIPOLICY` (
  `POLICY_ID` VARCHAR(50) NOT NULL,
  `POLICY_NAME` VARCHAR(100) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `PHASE` VARCHAR(30) NOT NULL,
  `STATUS` VARCHAR(30) NOT NULL,
  `DEL_DEADLINE` INT NOT NULL,
  `DEL_DEADLINE_UNIT` VARCHAR(5) NOT NULL,
  `ARCHIVE_FLAG` VARCHAR(1) NOT NULL,
  `ARC_DEL_DEADLINE` INT,
  `ARC_DEL_DEADLINE_UNIT` VARCHAR(5),
  `RELATED_LAW` VARCHAR(500),
  `COMMENTS` VARCHAR(2000),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  PRIMARY KEY (`POLICY_ID`, `VERSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIEXTRACT
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIEXTRACT`;
CREATE TABLE `COTDL`.`TBL_PIIEXTRACT` (
  `ORDERID` INT NOT NULL,
  `JOBID` VARCHAR(200) NOT NULL,
  `ACTID` VARCHAR(50) NOT NULL,
  `CUSTID` VARCHAR(50) NOT NULL,
  `BASEDATE` DATETIME NOT NULL,
  `EXCLUDE_REASON` VARCHAR(30),
  `ACTROLE_END_DATE` DATETIME,
  `ARCHIVE_DATE` DATETIME,
  `DELETE_DATE` DATETIME,
  `RESTORE_DATE` DATETIME,
  `ARC_DEL_DATE` DATETIME,
  `LAST_BASE_DATE` DATETIME,
  `EXPECTED_ARC_DEL_DATE` DATETIME,
  `CUST_NM` VARCHAR(50),
  `BIRTH_DT` VARCHAR(8),
  `ADDRESS` VARCHAR(200),
  `RSDNT_ALTRNTV_ID` VARCHAR(13),
  `CUST_PIN` VARCHAR(128),
  `INST_CD` VARCHAR(10),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  `VAL1` VARCHAR(50),
  `VAL2` VARCHAR(50),
  `VAL3` VARCHAR(50),
  `VAL4` VARCHAR(50),
  `VAL5` VARCHAR(50),
  `VAL6` VARCHAR(50),
  `VAL7` VARCHAR(50),
  PRIMARY KEY (`ORDERID`, `JOBID`, `ACTID`, `CUSTID`, `BASEDATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIICONTRACT
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIICONTRACT`;
CREATE TABLE `COTDL`.`TBL_PIICONTRACT` (
  `CUSTID` VARCHAR(50) NOT NULL,
  `CONTRACTNO` VARCHAR(100) NOT NULL,
  `DEPT_CD` VARCHAR(20) NOT NULL,
  `DEPT_NAME` VARCHAR(50) NOT NULL,
  `MGMT_DEPT_CD` VARCHAR(20) NOT NULL,
  `MGMT_DEPT_NAME` VARCHAR(50) NOT NULL,
  `CONTRACT_OPN_DT` DATETIME,
  `CONTRACT_CLOSE_DT` DATETIME,
  `PD_CD` VARCHAR(50),
  `PD_NM` VARCHAR(50),
  `STATUS` VARCHAR(10) NOT NULL,
  `ACTID` VARCHAR(50),
  `RSDNT_ALTRNTV_ID` VARCHAR(64),
  `CUST_NM` VARCHAR(50),
  `BIRTH_DT` VARCHAR(8),
  `CB_DT` VARCHAR(8),
  `CUST_PIN` VARCHAR(128),
  `INST_CD` VARCHAR(10),
  `BASEDATE` DATETIME,
  `ACTROLE_END_DATE` DATETIME,
  `ARCHIVE_DATE` DATETIME,
  `DELETE_DATE` DATETIME,
  `ARC_DEL_DATE` DATETIME,
  `REAL_DOC_DEL_DATE` DATETIME,
  `REAL_DOC_DEL_USERID` VARCHAR(10),
  PRIMARY KEY (`CUSTID`, `CONTRACTNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIICONFIG
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIICONFIG`;
CREATE TABLE `COTDL`.`TBL_PIICONFIG` (
  `CFGKEY` VARCHAR(50) NOT NULL,
  `VALUE` VARCHAR(4000) NOT NULL,
  `COMMENTS` VARCHAR(1000),
  PRIMARY KEY (`CFGKEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIBIZDAY
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIBIZDAY`;
CREATE TABLE `COTDL`.`TBL_PIIBIZDAY` (
  `BASE_DT` VARCHAR(8) NOT NULL,
  `BF_BF_BIZ_DT` VARCHAR(8),
  `BF_BIZ_DT` VARCHAR(8),
  `BIZ_dT` VARCHAR(8),
  `NXT_BIZ_DT` VARCHAR(8),
  `NXT_NXT_BIZ_DT` VARCHAR(8),
  `HLDY_YN` VARCHAR(1) NOT NULL,
  `INST_CD` VARCHAR(14),
  PRIMARY KEY (`BASE_DT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIBIZDAY_TMP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIBIZDAY_TMP`;
CREATE TABLE `COTDL`.`TBL_PIIBIZDAY_TMP` (
  `BASE_DT` VARCHAR(8) NOT NULL,
  `BF_BF_BIZ_DT` VARCHAR(8),
  `BF_BIZ_DT` VARCHAR(8),
  `BIZ_dT` VARCHAR(8),
  `NXT_BIZ_DT` VARCHAR(8),
  `NXT_NXT_BIZ_DT` VARCHAR(8),
  `HLDY_YN` VARCHAR(1) NOT NULL,
  `INST_CD` VARCHAR(14),
  PRIMARY KEY (`BASE_DT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIBIZDAY_NEW
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIBIZDAY_NEW`;
CREATE TABLE `COTDL`.`TBL_PIIBIZDAY_NEW` (
  `BASE_DT` VARCHAR(8) NOT NULL,
  `BF_BF_BIZ_DT` VARCHAR(8),
  `BF_BIZ_DT` VARCHAR(8),
  `BIZ_dT` VARCHAR(8),
  `NXT_BIZ_DT` VARCHAR(8),
  `NXT_NXT_BIZ_DT` VARCHAR(8),
  `HLDY_YN` VARCHAR(1) NOT NULL,
  `INST_CD` VARCHAR(14),
  PRIMARY KEY (`BASE_DT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIBIZDAY_OLD
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIBIZDAY_OLD`;
CREATE TABLE `COTDL`.`TBL_PIIBIZDAY_OLD` (
  `BASE_DT` VARCHAR(8) NOT NULL,
  `BF_BF_BIZ_DT` VARCHAR(8),
  `BF_BIZ_DT` VARCHAR(8),
  `BIZ_dT` VARCHAR(8),
  `NXT_BIZ_DT` VARCHAR(8),
  `NXT_NXT_BIZ_DT` VARCHAR(8),
  `HLDY_YN` VARCHAR(1) NOT NULL,
  `INST_CD` VARCHAR(14),
  PRIMARY KEY (`BASE_DT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIISTEPTABLEUPDATE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIISTEPTABLEUPDATE`;
CREATE TABLE `COTDL`.`TBL_PIISTEPTABLEUPDATE` (
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `STEPID` VARCHAR(100) NOT NULL,
  `SEQ1` INT NOT NULL,
  `SEQ2` INT NOT NULL,
  `SEQ3` INT NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `UPDATE_VAL` VARCHAR(100),
  `STATUS` VARCHAR(30),
  PRIMARY KEY (`JOBID`, `VERSION`, `STEPID`, `SEQ1`, `SEQ2`, `SEQ3`, `COLUMN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIORDERSTEPTABLEUPDATE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIORDERSTEPTABLEUPDATE`;
CREATE TABLE `COTDL`.`TBL_PIIORDERSTEPTABLEUPDATE` (
  `ORDERID` INT NOT NULL,
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `STEPID` VARCHAR(100) NOT NULL,
  `SEQ1` INT NOT NULL,
  `SEQ2` INT NOT NULL,
  `SEQ3` INT NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `UPDATE_VAL` VARCHAR(100),
  `STATUS` VARCHAR(30),
  PRIMARY KEY (`ORDERID`, `JOBID`, `VERSION`, `STEPID`, `SEQ1`, `SEQ2`, `SEQ3`, `COLUMN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_METATABLE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_METATABLE`;
CREATE TABLE `COTDL`.`TBL_METATABLE` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_ID` INT NOT NULL,
  `PK_YN` VARCHAR(1),
  `PK_POSITION` INT,
  `FULL_DATA_TYPE` VARCHAR(100),
  `DATA_TYPE` VARCHAR(100) NOT NULL,
  `DATA_LENGTH` INT,
  `DOMAIN` VARCHAR(50),
  `PIITYPE` VARCHAR(50),
  `PIIGRADE` VARCHAR(10),
  `ENCRIPT_FLAG` VARCHAR(1),
  `SCRAMBLE_TYPE` VARCHAR(50),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  `MASTERKEY` VARCHAR(30),
  `MASTERYN` VARCHAR(1),
  `TABLE_COMMENT` VARCHAR(255),
  `COLUMN_COMMENT` VARCHAR(255),
  `VAL1` VARCHAR(100),
  `VAL2` VARCHAR(100),
  `VAL3` VARCHAR(100),
  `VAL4` VARCHAR(100),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_METATABLE_TMP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_METATABLE_TMP`;
CREATE TABLE `COTDL`.`TBL_METATABLE_TMP` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_ID` INT NOT NULL,
  `PK_YN` VARCHAR(1),
  `PK_POSITION` INT,
  `FULL_DATA_TYPE` VARCHAR(100),
  `DATA_TYPE` VARCHAR(100) NOT NULL,
  `DATA_LENGTH` INT,
  `DOMAIN` VARCHAR(50),
  `PIITYPE` VARCHAR(50),
  `PIIGRADE` VARCHAR(10),
  `ENCRIPT_FLAG` VARCHAR(1),
  `SCRAMBLE_TYPE` VARCHAR(50),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  `MASTERKEY` VARCHAR(30),
  `MASTERYN` VARCHAR(1),
  `TABLE_COMMENT` VARCHAR(255),
  `COLUMN_COMMENT` VARCHAR(255),
  `VAL1` VARCHAR(100),
  `VAL2` VARCHAR(100),
  `VAL3` VARCHAR(100),
  `VAL4` VARCHAR(100),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_METATABLE_NEW
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_METATABLE_NEW`;
CREATE TABLE `COTDL`.`TBL_METATABLE_NEW` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_ID` INT NOT NULL,
  `PK_YN` VARCHAR(1),
  `PK_POSITION` INT,
  `FULL_DATA_TYPE` VARCHAR(100),
  `DATA_TYPE` VARCHAR(100) NOT NULL,
  `DATA_LENGTH` INT,
  `DOMAIN` VARCHAR(50),
  `PIITYPE` VARCHAR(50),
  `PIIGRADE` VARCHAR(10),
  `ENCRIPT_FLAG` VARCHAR(1),
  `SCRAMBLE_TYPE` VARCHAR(50),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  `MASTERKEY` VARCHAR(30),
  `MASTERYN` VARCHAR(1),
  `TABLE_COMMENT` VARCHAR(255),
  `COLUMN_COMMENT` VARCHAR(255),
  `VAL1` VARCHAR(100),
  `VAL2` VARCHAR(100),
  `VAL3` VARCHAR(100),
  `VAL4` VARCHAR(100),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_METATABLE_OLD
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_METATABLE_OLD`;
CREATE TABLE `COTDL`.`TBL_METATABLE_OLD` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_ID` INT NOT NULL,
  `PK_YN` VARCHAR(1),
  `PK_POSITION` INT,
  `FULL_DATA_TYPE` VARCHAR(100),
  `DATA_TYPE` VARCHAR(100) NOT NULL,
  `DATA_LENGTH` INT,
  `DOMAIN` VARCHAR(50),
  `PIITYPE` VARCHAR(50),
  `PIIGRADE` VARCHAR(10),
  `ENCRIPT_FLAG` VARCHAR(1),
  `SCRAMBLE_TYPE` VARCHAR(50),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  `MASTERKEY` VARCHAR(30),
  `MASTERYN` VARCHAR(1),
  `TABLE_COMMENT` VARCHAR(255),
  `COLUMN_COMMENT` VARCHAR(255),
  `VAL1` VARCHAR(100),
  `VAL2` VARCHAR(100),
  `VAL3` VARCHAR(100),
  `VAL4` VARCHAR(100),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIDETECT_CONFIG
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIDETECT_CONFIG`;
CREATE TABLE `COTDL`.`TBL_PIIDETECT_CONFIG` (
  `CONF_ID` VARCHAR(100) NOT NULL,
  `CONF_NAME` VARCHAR(200) NOT NULL,
  `DETECT_TYPE` VARCHAR(100),
  `DETECT_PATTERN1` VARCHAR(150),
  `DETECT_PATTERN2` VARCHAR(150),
  `DETECT_PATTERN3` VARCHAR(150),
  `DETECT_PATTERN4` VARCHAR(150),
  `DETECT_PATTERN5` VARCHAR(150),
  `DETECT_PATTERN6` VARCHAR(150),
  `DETECT_PATTERN7` VARCHAR(150),
  `DETECT_PATTERN8` VARCHAR(150),
  `LENTH_MIN` INT NOT NULL,
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  PRIMARY KEY (`CONF_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIDETECT_RESULT
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIDETECT_RESULT`;
CREATE TABLE `COTDL`.`TBL_PIIDETECT_RESULT` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `ORDERID` INT NOT NULL,
  `PIITYPE` VARCHAR(13),
  `PIICNT` INT,
  `DETECT_ALL_CNT` INT,
  `PII_RATIO` INT,
  `REGDATE` DATETIME,
  `SAMPLEDATA` VARCHAR(1000),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`, `ORDERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIDETECT_RESULT_TMP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIDETECT_RESULT_TMP`;
CREATE TABLE `COTDL`.`TBL_PIIDETECT_RESULT_TMP` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `ORDERID` INT NOT NULL,
  `PIITYPE` VARCHAR(13),
  `PIICNT` INT,
  `DETECT_ALL_CNT` INT,
  `PII_RATIO` INT,
  `REGDATE` DATETIME,
  `SAMPLEDATA` VARCHAR(1000),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`, `ORDERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIDETECT_RESULT_NEW
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIDETECT_RESULT_NEW`;
CREATE TABLE `COTDL`.`TBL_PIIDETECT_RESULT_NEW` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `ORDERID` INT NOT NULL,
  `PIITYPE` VARCHAR(13),
  `PIICNT` INT,
  `DETECT_ALL_CNT` INT,
  `PII_RATIO` INT,
  `REGDATE` DATETIME,
  `SAMPLEDATA` VARCHAR(1000),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`, `ORDERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIDETECT_RESULT_OLD
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIDETECT_RESULT_OLD`;
CREATE TABLE `COTDL`.`TBL_PIIDETECT_RESULT_OLD` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `COLUMN_NAME` VARCHAR(128) NOT NULL,
  `ORDERID` INT NOT NULL,
  `PIITYPE` VARCHAR(13),
  `PIICNT` INT,
  `DETECT_ALL_CNT` INT,
  `PII_RATIO` INT,
  `REGDATE` DATETIME,
  `SAMPLEDATA` VARCHAR(1000),
  PRIMARY KEY (`DB`, `OWNER`, `TABLE_NAME`, `COLUMN_NAME`, `ORDERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIUPLOAD_TEMPLATE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIUPLOAD_TEMPLATE`;
CREATE TABLE `COTDL`.`TBL_PIIUPLOAD_TEMPLATE` (
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `STEPID` VARCHAR(100) NOT NULL,
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `EXETYPE` VARCHAR(10) NOT NULL,
  `SEQ` INT NOT NULL,
  `PK_COL` VARCHAR(200),
  `WHERE_COL` VARCHAR(200),
  `WHERE_KEY_NAME` VARCHAR(50),
  `PARALLELCNT` INT,
  `COMMITCNT` INT,
  `PRE_OWNER` VARCHAR(128),
  `PRE_TABLE_NAME` VARCHAR(128),
  `UPDATE_COLS` VARCHAR(4000),
  `PAGITYPEDETAIL` VARCHAR(10),
  PRIMARY KEY (`JOBID`, `VERSION`, `STEPID`, `SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIISTEPTABLE_ETC
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIISTEPTABLE_ETC`;
CREATE TABLE `COTDL`.`TBL_PIISTEPTABLE_ETC` (
  `JOBID` VARCHAR(200) NOT NULL,
  `VERSION` VARCHAR(10) NOT NULL,
  `STEPID` VARCHAR(100) NOT NULL,
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `PAGITYPE` VARCHAR(10),
  `PAGITYPEDETAIL` VARCHAR(10),
  `EXETYPE` VARCHAR(10) NOT NULL,
  `ARCHIVEFLAG` VARCHAR(1),
  `STATUS` VARCHAR(30),
  `PRECEDING` VARCHAR(30),
  `SUCCEDDING` VARCHAR(30),
  `SEQ1` INT NOT NULL,
  `SEQ2` INT NOT NULL,
  `SEQ3` INT NOT NULL,
  `PIPELINE` INT,
  `PK_COL` VARCHAR(200),
  `WHERE_COL` VARCHAR(200),
  `WHERE_KEY_NAME` VARCHAR(50),
  `PARALLELCNT` INT,
  `COMMITCNT` INT,
  `WHERESTR` TEXT,
  `SQLSTR` TEXT,
  `KEYMAP_ID` VARCHAR(50),
  `KEY_NAME` VARCHAR(50),
  `KEY_COLS` VARCHAR(200),
  `KEY_REFSTR` VARCHAR(500),
  `SQLTYPE` VARCHAR(10),
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  PRIMARY KEY (`JOBID`, `VERSION`, `STEPID`, `SEQ1`, `SEQ2`, `SEQ3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_DEPARTMENT
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_DEPARTMENT`;
CREATE TABLE `COTDL`.`TBL_DEPARTMENT` (
  `DEPTCODE` VARCHAR(100) NOT NULL,
  `DEPTNAME` VARCHAR(200) NOT NULL,
  `STATUS` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`DEPTCODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_DEPARTMENT_TMP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_DEPARTMENT_TMP`;
CREATE TABLE `COTDL`.`TBL_DEPARTMENT_TMP` (
  `DEPTCODE` VARCHAR(100) NOT NULL,
  `DEPTNAME` VARCHAR(200) NOT NULL,
  `STATUS` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`DEPTCODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_DEPARTMENT_NEW
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_DEPARTMENT_NEW`;
CREATE TABLE `COTDL`.`TBL_DEPARTMENT_NEW` (
  `DEPTCODE` VARCHAR(100) NOT NULL,
  `DEPTNAME` VARCHAR(200) NOT NULL,
  `STATUS` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`DEPTCODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_DEPARTMENT_OLD
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_DEPARTMENT_OLD`;
CREATE TABLE `COTDL`.`TBL_DEPARTMENT_OLD` (
  `DEPTCODE` VARCHAR(100) NOT NULL,
  `DEPTNAME` VARCHAR(200) NOT NULL,
  `STATUS` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`DEPTCODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIREPORT
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIREPORT`;
CREATE TABLE `COTDL`.`TBL_PIIREPORT` (
  `REPORTID` INT NOT NULL,
  `PHASE` VARCHAR(15),
  `APRVLINEID` VARCHAR(100) NOT NULL,
  `APPROVALID` VARCHAR(50) NOT NULL,
  `REPORT_TYPE` VARCHAR(30),
  `DATE_FROM` VARCHAR(10),
  `DATE_TO` VARCHAR(10),
  `VAL1` VARCHAR(50),
  `VAL2` VARCHAR(50),
  `VAL3` VARCHAR(50),
  `APPLY_DATE` DATETIME,
  `APPLY_USERID` VARCHAR(10),
  `APPROVE_DATE` DATETIME,
  `APPROVE_USERID` VARCHAR(10),
  PRIMARY KEY (`REPORTID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_MEMBER_TMP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_MEMBER_TMP`;
CREATE TABLE `COTDL`.`TBL_MEMBER_TMP` (
  `USERID` VARCHAR(50) NOT NULL,
  `USERPW` VARCHAR(100) NOT NULL,
  `USERNAME` VARCHAR(64) NOT NULL,
  `REGDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATEDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `ENABLED` CHAR(1) DEFAULT '1',
  `DEPT_CD` VARCHAR(20) NOT NULL,
  `DEPT_NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_MEMBER_NEW
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_MEMBER_NEW`;
CREATE TABLE `COTDL`.`TBL_MEMBER_NEW` (
  `USERID` VARCHAR(50) NOT NULL,
  `USERPW` VARCHAR(100) NOT NULL,
  `USERNAME` VARCHAR(64) NOT NULL,
  `REGDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATEDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `ENABLED` CHAR(1) DEFAULT '1',
  `DEPT_CD` VARCHAR(20) NOT NULL,
  `DEPT_NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_MEMBER_OLD
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_MEMBER_OLD`;
CREATE TABLE `COTDL`.`TBL_MEMBER_OLD` (
  `USERID` VARCHAR(50) NOT NULL,
  `USERPW` VARCHAR(100) NOT NULL,
  `USERNAME` VARCHAR(64) NOT NULL,
  `REGDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATEDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `ENABLED` CHAR(1) DEFAULT '1',
  `DEPT_CD` VARCHAR(20) NOT NULL,
  `DEPT_NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIICUSTSTAT
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIICUSTSTAT`;
CREATE TABLE `COTDL`.`TBL_PIICUSTSTAT` (
  `CHARTNAME` VARCHAR(50) NOT NULL,
  `MON` DATETIME NOT NULL,
  `ARCHIVE_CNT1` INT,
  `RESTORE_CNT1` INT,
  `ARC_DEL_CNT1` INT,
  `ARCHIVE_CNT2` INT,
  `RESTORE_CNT2` INT,
  `ARC_DEL_CNT2` INT,
  `ARCHIVE_CNT3` INT,
  `RESTORE_CNT3` INT,
  `ARC_DEL_CNT3` INT,
  PRIMARY KEY (`CHARTNAME`, `MON`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIICUSTSTATYEAR
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIICUSTSTATYEAR`;
CREATE TABLE `COTDL`.`TBL_PIICUSTSTATYEAR` (
  `CHARTNAME` VARCHAR(50) NOT NULL,
  `YM_11` VARCHAR(50) NOT NULL,
  `YM_10` VARCHAR(50) NOT NULL,
  `YM_9` VARCHAR(50) NOT NULL,
  `YM_8` VARCHAR(50) NOT NULL,
  `YM_7` VARCHAR(50) NOT NULL,
  `YM_6` VARCHAR(50) NOT NULL,
  `YM_5` VARCHAR(50) NOT NULL,
  `YM_4` VARCHAR(50) NOT NULL,
  `YM_3` VARCHAR(50) NOT NULL,
  `YM_2` VARCHAR(50) NOT NULL,
  `YM_1` VARCHAR(50) NOT NULL,
  `YM_0` VARCHAR(50) NOT NULL,
  `CNT_11` INT,
  `CNT_10` INT,
  `CNT_9` INT,
  `CNT_8` INT,
  `CNT_7` INT,
  `CNT_6` INT,
  `CNT_5` INT,
  `CNT_4` INT,
  `CNT_3` INT,
  `CNT_2` INT,
  `CNT_1` INT,
  `CNT_0` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIEXTRACT_PURGE_STAT  (퍼지된 레코드 통계 보존)
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIEXTRACT_PURGE_STAT`;
CREATE TABLE `COTDL`.`TBL_PIIEXTRACT_PURGE_STAT` (
  `STAT_DATE`    VARCHAR(10)  NOT NULL COMMENT 'YYYY/MM/DD 또는 YYYYMM',
  `STAT_TYPE`    VARCHAR(20)  NOT NULL COMMENT 'ARC_DEL, ARCHIVE, RESTORE_ALL, RESTORE, ARC_DEL_DELARC, ARC_DEL_DELARC_P, BASEDATE',
  `JOBID_PREFIX` VARCHAR(11)  NOT NULL COMMENT 'PII_POLICY1, PII_POLICY2, PII_POLICY3, ALL',
  `CNT`          INT          NOT NULL DEFAULT 0,
  `PURGE_DATE`   DATETIME     NOT NULL COMMENT '최종 퍼지 실행일',
  PRIMARY KEY (`STAT_DATE`, `STAT_TYPE`, `JOBID_PREFIX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIEXTRACT_PURGE_LOG  (퍼지된 고객별 파기 증적)
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIEXTRACT_PURGE_LOG`;
CREATE TABLE `COTDL`.`TBL_PIIEXTRACT_PURGE_LOG` (
  `CUSTID`       VARCHAR(50)  NOT NULL COMMENT '고객ID',
  `JOBID`        VARCHAR(200) NOT NULL COMMENT '파기 Job ID',
  `BASEDATE`     DATETIME     NOT NULL COMMENT '기준일',
  `ORDERID`      INT          NOT NULL COMMENT '오더ID',
  `ARC_DEL_DATE` DATETIME              COMMENT '영구파기일',
  `RESTORE_DATE` DATETIME              COMMENT '복원일',
  `EXCLUDE_REASON` VARCHAR(30)          COMMENT 'DELARC 또는 RESTORE',
  `PURGE_DATE`   DATETIME     NOT NULL COMMENT '실제 삭제(퍼지) 실행일',
  PRIMARY KEY (`CUSTID`, `JOBID`, `BASEDATE`, `ORDERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIICONTRACTSTAT
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIICONTRACTSTAT`;
CREATE TABLE `COTDL`.`TBL_PIICONTRACTSTAT` (
  `CHARTNAME` VARCHAR(50) NOT NULL,
  `MON` VARCHAR(50) NOT NULL,
  `MGMT_DEPT_CD` VARCHAR(50),
  `MGMT_DEPT_NAME` VARCHAR(100),
  `ACOUNT` INT,
  `NCOUNT` INT,
  `YCOUNT` INT,
  `PROGRESS` VARCHAR(50),
  PRIMARY KEY (`CHARTNAME`, `MON`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_INNERSTEP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_INNERSTEP`;
CREATE TABLE `COTDL`.`TBL_INNERSTEP` (
  `ORDERID` INT NOT NULL,
  `STEPID` VARCHAR(100) NOT NULL,
  `SEQ1` INT NOT NULL,
  `SEQ2` INT NOT NULL,
  `SEQ3` INT NOT NULL,
  `INNER_STEP_SEQ` INT NOT NULL,
  `INNER_STEP_NAME` VARCHAR(50),
  `STATUS` VARCHAR(30),
  `EXECNT` BIGINT,
  `EXETIME` VARCHAR(20),
  `EXESTART` DATETIME,
  `EXEEND` DATETIME,
  `MESSAGE` VARCHAR(1000),
  `RESULT` VARCHAR(200),
  PRIMARY KEY (`ORDERID`, `STEPID`, `SEQ1`, `SEQ2`, `SEQ3`, `INNER_STEP_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_ORDERDDL
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_ORDERDDL`;
CREATE TABLE `COTDL`.`TBL_ORDERDDL` (
  `ORDERID` INT NOT NULL,
  `STEPID` VARCHAR(100) NOT NULL,
  `SEQ1` INT NOT NULL,
  `SEQ2` INT NOT NULL,
  `SEQ3` INT NOT NULL,
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TABLE_NAME` VARCHAR(128) NOT NULL,
  `CONSTRAINT_TYPE` VARCHAR(30),
  `OBJECT_TYPE` VARCHAR(128) NOT NULL,
  `OBJECT_OWNER` VARCHAR(128) NOT NULL,
  `OBJECT_NAME` VARCHAR(128) NOT NULL,
  `STATUS` VARCHAR(30),
  `RESULT` VARCHAR(100),
  `DDL` TEXT,
  PRIMARY KEY (`ORDERID`, `STEPID`, `SEQ1`, `SEQ2`, `SEQ3`, `OBJECT_TYPE`, `OBJECT_OWNER`, `OBJECT_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_LKPIISCRTYPE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_LKPIISCRTYPE`;
CREATE TABLE `COTDL`.`TBL_LKPIISCRTYPE` (
  `PIICODE` VARCHAR(100) NOT NULL,
  `PIIGRADEID` INT NOT NULL,
  `PIIGRADENAME` VARCHAR(10) NOT NULL,
  `PIIGROUPID` INT NOT NULL,
  `PIIGROUPNAME` VARCHAR(200) NOT NULL,
  `PIITYPEID` VARCHAR(200) NOT NULL,
  `PIITYPENAME` VARCHAR(200) NOT NULL,
  `SCRTYPE` VARCHAR(100) NOT NULL,
  `SCRMETHOD` VARCHAR(100) NOT NULL,
  `SCRCATEGORY` VARCHAR(100) NOT NULL,
  `SCRDIGITS` VARCHAR(100),
  `SCRVALIDITY` VARCHAR(100),
  `REMARKS` VARCHAR(300),
  `ENCDECFUNCTYPE` VARCHAR(10),
  `ENCFUNC` VARCHAR(100),
  `DECFUNC` VARCHAR(100),
  PRIMARY KEY (`PIICODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_TESTDATA
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_TESTDATA`;
CREATE TABLE `COTDL`.`TBL_TESTDATA` (
  `TESTDATAID` INT NOT NULL,
  `SYSTEM` VARCHAR(30),
  `SOURCEDB` VARCHAR(100),
  `TARGETDB` VARCHAR(100),
  `PHASE` VARCHAR(15),
  `APPLY_TYPE` VARCHAR(30),
  `NEW_ORDERID` INT,
  `JOBID` VARCHAR(200),
  `IDTYPE` VARCHAR(100),
  `CUSTID` VARCHAR(500),
  `CUSTID_NEW` VARCHAR(1000),
  `CUST_NM` VARCHAR(100),
  `SSN` VARCHAR(256),
  `NEW_JOBID` VARCHAR(200),
  `STATUS` VARCHAR(30),
  `APPROVE_DATE` DATETIME,
  `REGDATE` DATETIME,
  `UPDDATE` DATETIME,
  `REGUSERID` VARCHAR(10),
  `UPDUSERID` VARCHAR(10),
  `DISPOSAL_STATUS` VARCHAR(30),
  `DISPOSAL_SCHE_DATE` DATETIME,
  `DISPOSAL_EXEC_DATE` DATETIME,
  PRIMARY KEY (`TESTDATAID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PIIMASTERKEYMAP
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PIIMASTERKEYMAP`;
CREATE TABLE `COTDL`.`TBL_PIIMASTERKEYMAP` (
  `ORDERID` INT,
  `DB` VARCHAR(30),
  `KEY_NAME` VARCHAR(50),
  `BASEDATE` DATETIME,
  `CUSTID` VARCHAR(50),
  `VAL1` VARCHAR(255),
  `NEWVAL1` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_TESTDATAIDTYPE
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_TESTDATAIDTYPE`;
CREATE TABLE `COTDL`.`TBL_TESTDATAIDTYPE` (
  `ID` VARCHAR(100) NOT NULL,
  `IDNAME` VARCHAR(200),
  `SQLSTR` VARCHAR(4000),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_METASYSTEMDATA
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_METASYSTEMDATA`;
CREATE TABLE `COTDL`.`TBL_METASYSTEMDATA` (
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `DBINSTANCE_NM` VARCHAR(100) NOT NULL,
  `TAB_NAME_KR` VARCHAR(255),
  `TAB_NAME` VARCHAR(255) NOT NULL,
  `COL_NAME_KR` VARCHAR(255),
  `COL_NAME` VARCHAR(255) NOT NULL,
  `COL_REQ_USER` VARCHAR(50),
  `COL_REQ_DATE` DATETIME,
  `COL_APPR_USER` VARCHAR(50),
  `COL_APPR_DATE` DATETIME,
  `ATTR_NAME` VARCHAR(50),
  `IS_PK` CHAR(1),
  `IS_FK` CHAR(1),
  `IS_NULL` CHAR(1),
  `SRC_DECRYPT` CHAR(1),
  `TGT_ENCRYPT` CHAR(1),
  `IS_ENCRYPT` CHAR(1),
  `MGMT_TYPE` VARCHAR(50),
  `DOMAIN` VARCHAR(50),
  `DOMAIN_KR` VARCHAR(50),
  `DMNGRP_NM` VARCHAR(50),
  `INFOTYPE_NM` VARCHAR(50),
  `PII_ENC_INFO` VARCHAR(50),
  PRIMARY KEY (`DB`, `OWNER`, `TAB_NAME`, `COL_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_REPORT_JSON
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_REPORT_JSON`;
CREATE TABLE `COTDL`.`TBL_REPORT_JSON` (
  `SRVY_ID` VARCHAR(15) NOT NULL,
  `FORM_NAME` VARCHAR(100) NOT NULL,
  `FORM_JSON` JSON,
  `INPUT_JSON` JSON,
  `CREATED_AT` DATETIME,
  PRIMARY KEY (`SRVY_ID`, `FORM_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_METAPIISTATUS
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_METAPIISTATUS`;
CREATE TABLE `COTDL`.`TBL_METAPIISTATUS` (
  `SYSTEM_NAME` VARCHAR(100) NOT NULL,
  `DB` VARCHAR(100) NOT NULL,
  `OWNER` VARCHAR(128) NOT NULL,
  `TOTAL_TABLES` INT,
  `TOTAL_COLUMNS` INT NOT NULL,
  `PII_NOTCONFIRMED` INT,
  `PII_TABLES` INT NOT NULL,
  `PII_COLUMNS` INT,
  `PII3_DEL_COLUMNS` INT,
  `PII3_UPD_COLUMNS` INT,
  `PII3_NOTREGISTERED` INT,
  `PII3_NOTREGISTERED_PERCENTAGE` INT,
  PRIMARY KEY (`SYSTEM_NAME`, `DB`, `OWNER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_ERRORHIST
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_ERRORHIST`;
CREATE TABLE `COTDL`.`TBL_ERRORHIST` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `MODULE_NAME` VARCHAR(100),
  `ERROR_MESSAGE` TEXT,
  `STACK_TRACE` TEXT,
  `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ------------------------------------------------------------
-- TBL_PROGORDERHIST
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `COTDL`.`TBL_PROGORDERHIST`;
CREATE TABLE `COTDL`.`TBL_PROGORDERHIST` (
  `ORDERID` BIGINT NOT NULL,
  `PROG_JOB_NM` VARCHAR(100) NOT NULL,
  `BGNN_CHNG_DVCD` VARCHAR(10) NOT NULL,
  `PARAM_BASE_DT` VARCHAR(10) NOT NULL,
  `DB` VARCHAR(100) NOT NULL,
  `UPDATE_QUERY` VARCHAR(2000) NOT NULL,
  `INSERT_QUERY` VARCHAR(4000) NOT NULL,
  `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `ERROR_MESSAGE` VARCHAR(4000),
  PRIMARY KEY (`ORDERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
